### ISSUE TITLE
Extend TidbCluster v1alpha to support the spec of pump, configuration and discovery service

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1159]
## Proposal

As per #1121 , we want to extend TidbCluster Resource to replace  (or part of) the helm chart.

example:

```
apiVersion: pingcap.com/v1alpha2
kind: TidbCluster
metadata: {...}
spec:
 version: v3.0.5             # default: latest recommended stable version
 pd:
   baseImage: pingcap/pd     # default
   replicas: 3               # required
   resources: {...}          # default: {}
   config:
     log:
       level: info           # default
 tikv: {...}
 tidb: {...}
 pump: {...}
```
