### ISSUE TITLE
Add env spec to support custom starting script

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1392]
## Feature Request

**Is your feature request related to a problem? Please describe:**
To support  custom  `--advertise-client-urls` config in pd start script and `--advertise-addr` in tikv start script, we can add `env` spec every type of node. It will help us custom node start args.

For example , we can design tidbcluster yaml like the following :

```
tikv:
  # Built-in environment variables have  POD_NAME  HEADLESS_SERVICE_NAME NAMESPACE etc.
  env:
     ADVERTISE_ADDR: $POD_NAME.$HEADLESS_SERVICE_NAME.$NAMESPACE.svc.xx.xx.com 
```

And the tikv start script can be rewrite like the following:

```
--advertise-addr=${ADVERTISE_ADDR:-$POD_NAME.$HEADLESS_SERVICE_NAME.$NAMESPACE.svc}:20160 
```

**Comment by tennix** [comment]
Yes, after we migrated our startup script to the controller, users cannot easily customize the startup script. Adding env for this would be helpful. But just curious why you would want to customize this advertise address?

**Comment by mikechengwei** [comment]
The server advertise address is used as  client traffic from outside access. 
 I sync k8s dns info to my company dns server, which cause I need to append my k8s domain to advertise address .Because client connect to pd nodes,the pd nodes return tikv `$POD_NAME.$HEADLESS_SERVICE_NAME.$NAMESPACE.svc` address. It can't be idenfied by company dns server. I must add company dns domain.

**Comment by aylei** [comment]
Template expose too much details of the start script to users, how about summarize common patterns and expose enum options to user, for example, `[default, fqdn]` etc.

**Comment by mikechengwei** [comment]
@aylei Do you mean we provide mutiple deploy options include default domain and fqdn ? Not use env for custom advertise address ,right?

**Comment by aylei** [comment]
First, this option is better to be a field in `TidbCluster` instead of an env KV, e.g.

```
spec:
  tikv:
    clientAddrFormat: fqdn
```

And we should still expose the configuration via environment variable in the start script, so, the CRD level field is mapped to an env var of the container:

```
containers:
- name: xx
   image: xxxx
   env:
     - name: CLIENT_ADDR_FORMAT
        value: fqdn
```
