### ISSUE TITLE
Update statefulset should retain the last-applied-configuration

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1475]
## Bug Report

#1414 will trigger rolling-update of legacy cluster because the annotations of the old cluster are totally overridden:

Before:
```
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "2379"
          prometheus.io/scrape: "true"
```

After upgrading operator:
```
        annotations:
          pingcap.com/last-applied-configuration: '{"volumes"....'
          prometheus.io/path: /metrics
          prometheus.io/port: "2379"
          prometheus.io/scrape: "true"
```
Though we do not set this annotation anymore, we should keep this during update to keep the backward compatibility.
