### ISSUE TITLE
no default for `.spec.clusterRef.namespace` of TiDB monitor

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1480]
There is no default for `.spec.clusterRef.namespace` of TiDB monitor, which could be default to the local namespace (where the `TidbMonitor` located) to reduce the configuration complexity.

e.g.

I want to deploy `tidbmonitor` and `tidbcluster` in one yaml:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v3.0.7
  imagePullPolicy: IfNotPresent
  pvReclaimPolicy: Delete
  schedulerName: "tidb-scheduler"
  timezone: "Asia/Shanghai"
  pd:
    baseImage: pingcap/pd
    replicas: 3
    storageClassName: shared-nvme-disks
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    storageClassName: shared-nvme-disks
    requests:
      storage: "50Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    service:
      type: NodePort
    config: {}
---
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
  - name: basic
  persistent: false
  prometheus:
    baseImage: prom/prometheus
    version: v2.11.1
  grafana:
    baseImage: grafana/grafana
    version: 6.0.1
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v3.0.5
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
```

The namespace of these 2 resources are not determined until I actually apply them with

```
> kubectl apply -n my-ns -f ./
```

But this way I will not get the monitoring Pod get created because the `namespace` is empty -- therefore, the cluster referenced by the tidbmonitor could not be found. **I have to modify the yaml to set the namespace to "my-ns"** first, and actually I have to rollback this change after apply because I don't want the YAML definition to be coupled with specific namespace.
