### ISSUE TITLE
distinguish peer service and external service with labels.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#2164]
## Feature Request
Is your feature request related to a problem?

When I use prometheus operator to monitor tidb, I can't distinguish peer service and external service with labels. Prometheus operator will scrape duplicate data.
Prometheus ServiceMonitor config below:

  ```
selector:
    matchLabels:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: basic
```

Prometheus screenshot below:
![image](https://user-images.githubusercontent.com/13257127/79095420-eccd6a80-7d8c-11ea-8c2a-bd1fdbbc03d0.png)

Prometheus operator feature pr can refer to #2163 
**Describe the feature you'd like:**
Add label app.kubernetes.io/headless=true  or false value.
