### ISSUE TITLE
UCP: support mount external prometheus configs in TidbMonitor

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2180]
## Description
Close https://github.com/pingcap/tidb-operator/issues/2175

We could support customize TidbMonitor's prometheus configs by mount the external configmaps.

We could add a new property like `.spec.prometheus.config.externalConfigMaps` to indicate TidbMonitor controller mount this external configmap for prometheus configs.

it should contain the design on what kinds of argument we need to expose and explain why.

## Score

* 300

## Mentor(s)

* [@yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills
* Golang
* Kubernetes

**Comment by mikechengwei** [comment]
Hi, it's my feature design.
User create custom configMap, we replace default prometheus configMap with user configMap.
Config option design : 
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: demo
spec:
  clusters:
  - name: demo
  prometheus:
    externalConfigMaps:
      config: prometheus-config
    baseImage: prom/prometheus
    version: v2.11.1
```
Will we support rule config later?

**Comment by mikechengwei** [comment]
Or like
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: demo
spec:
  clusters:
  - name: demo
  prometheus:
    externalConfigMaps: <configMap name>
    baseImage: prom/prometheus
    version: v2.11.1
```
just replace prometheus config.
