### ISSUE TITLE
TiKV Pod supports multiple PVCs 

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2183]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiKV Pod supports multiple PVCs so that Titan can be enabled with a separate disk.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
use case: https://github.com/pingcap/tidb-operator/issues/1357

**Comment by mikechengwei** [comment]
mark

**Comment by mikechengwei** [comment]
My design:

```
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        wal-dir: "/var/lib/wal"
      titan:
        dirname: "/var/lib/titan"      
    volume:
      - name: wal
        storageClassName: local-storage
        storage: "2Gi"
        mountPath: "/val/lib/wal"
      - name: titan
        # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
        storage: "2Gi"
        mountPath: "/var/lib/titan"
```
