### ISSUE TITLE
Can't login TiDB dashboard on Kind.

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#2212]
## Bug Report

**What version of Kubernetes are you using?**

1.17

**What version of TiDB Operator are you using?**

Master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

All Pods are Running.

**What did you do?**

Using Kind:
1. ```kubectl  -n t1 apply -f examples/basic/tidb-cluster.yaml```
2. Modify PD & TiDB svc as NodePort
3. Using NAT forward port to PD svc NodePort ```socat TCP-LISTEN:30108,fork TCP:172.17.0.2:30108```
4. Login TiDB dashboard in Chrome.

**What did you expect to see?**
Login dashboard.

**What did you see instead?**
Got this error in browser:
```
message: "authenticate failed, cause: error.tidb.tidb_conn_failed: failed to connect to TiDB, cause: dial tcp 0.0.0.0:4000: connect: connection refused"
```

**Comment by DanielZhangQD** [comment]
@shonge What tidb version do you use? Please try v4.0.0-rc if not.
@LinuxGit Anything that we need to set for Dashboard?

**Comment by shonge** [comment]
spec:
    pd:
      baseImage: pingcap/pd
      config: {}
      replicas: 1
      requests:
        storage: 1Gi
    pvReclaimPolicy: Delete
    tidb:
      baseImage: pingcap/tidb
      config: {}
      replicas: 1
      service:
        type: NodePort
    tikv:
      baseImage: pingcap/tikv
      config: {}
      replicas: 3
      requests:
        storage: 1Gi
    timezone: UTC
    version: nightly

**Comment by DanielZhangQD** [comment]
```
Using NAT forward port to PD svc NodePort socat TCP-LISTEN:30108,fork TCP:172.17.0.2:30108
```
You are not using `kubectl port-forward`? 
The NodePort for kind is not exposed on the PC or VM that running the kind cluster, it's on the kind workers.

**Comment by shonge** [comment]
```
kubectl -n t1 port-forward --address 0.0.0.0 pod/basic-pd-0 2379
kubectl -n t1 port-forward --address 0.0.0.0 pod/basic-tidb-0 4000
```
Same error:
"authenticate failed, cause: error.tidb.tidb_conn_failed: failed to connect to TiDB, cause: dial tcp 0.0.0.0:4000: connect: connection refused"

**Comment by Yisaer** [comment]
Hi, @shonge , I test dashboard with kind and latest operator, it worked well in my env. Here is my tidbcluster yaml
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test
spec:
  #  version: latest
  timezone: UTC
#  tlsCluster:
#    enabled: true
  pvReclaimPolicy: Delete
  imagePullPolicy: IfNotPresent
  pd:
    image: pingcap/pd:v4.0.0-rc
    replicas: 1
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    config: {}
    image: pingcap/tikv:v4.0.0-rc
    replicas: 1
    requests:
      storage: "1Gi"
  tidb:
    enableAdvertiseAddress: true
    image: pingcap/tidb:v4.0.0-rc
    imagePullPolicy: IfNotPresent
    replicas: 1
    service:
      type: ClusterIP
    config: {}
    requests:
      cpu: 1
```
After tidbcluster created, use `kubectl port-forward svc/test-pd 2379:2379` and visit `http://localhost:2379/dashboard`,here is what I see:

![isee](https://user-images.githubusercontent.com/13427348/80348257-1c599800-88a0-11ea-9338-e7dc15337861.png)
