### ISSUE TITLE
How to change the configuration of TiDB/TiKV/Pd on the fly?

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/tidb-operator#225]
I notice there's no related information in TiDB Cluster Operation Guide

**Comment by tennix** [comment]
Currently, pods will not be recreated when config file changes. We can achieve this by calculating sha256sum of configmap as documented here https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

**Comment by tennix** [comment]
Since we store the startup script and configuration file in a `ConfigMap`. Either of this two parts changes, we should recreate the pod to apply modifications. From the link I mentioned above, we can achieve reloading configuration via the following method:

Add `ConfigMap` checksum as annotations in `TidbCluster`:
```yaml
  annotations:
    checksum/pd-config: {{ include (print $.Template.BasePath "/pd-configmap.yaml") . | sha256sum }}
    checksum/tikv-config: {{ include (print $.Template.BasePath "/tikv-configmap.yaml") . | sha256sum }}
    checksum/tidb-config: {{ include (print $.Template.BasePath "/tidb-configmap.yaml") . | sha256sum }}
```
The tidb cluster controller checks these annotations periodicaly, if there is a checksum changes, updating the corresponding `StatefulSet` annotations. This triggers the `StatefulSet` controller recreating the managed pods. Thus achieving changing configuration on the fly.

I've tested that the `checksum/tikv-config` would change when changing TiKV `syncLog` to `false`. So this approach should work for us.
