### ISSUE TITLE
No named port for tikv metrics port

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb-operator#2410]
There is no container port set up for the tikv metrics port 20180:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    prometheus.io/path: /metrics
    prometheus.io/port: "20180"
...
    ports:
    - containerPort: 20160
      name: server
      protocol: TCP
```

**Comment by DanielZhangQD** [comment]
@tirsen Yes, it's not set explicitly in the yaml, but the metrics can be pulled by Prometheus, do you have any issues with the current yaml settings?

**Comment by tirsen** [comment]
No I realized I can use `targetPort` instead so it's all good.

**Comment by DanielZhangQD** [comment]
OK, feel free to let us know if any more issues, thanks!

**Comment by tirsen** [comment]
Actually using`targetPort` doesn't look like it's working with prometheus-operator. It needs a named port.

**Comment by Yisaer** [comment]
Recently the community have contributed the example of prometheus-operator to monitor tidbcluster.  It seems ok for this community user in his situation. @tirsen  Could you provide your prometheus-operator version that I can test whether it is necessary.

https://github.com/pingcap/tidb-operator/tree/master/examples/prometheus-operator

**Comment by yeya24** [comment]
@tirsen Hello, you can achieve that without adding status port by relabeling. Example `ServiceMonitor`. I just tested in my environment and it works well. Could you please try it?

``` yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: basic-tikv
spec:
  endpoints:
  - interval: 15s
    scrapeTimeout: 10s
    path: /metrics
    relabelings:
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      regex: ([^:]+)(?::\d+)?;(\d+)
      targetLabel: __address__
      replacement: $1:$2
      action: replace
    metricRelabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      action: keep
      regex: basic
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
      action: keep
      regex: tikv
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: 'true'
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      targetLabel: __metrics_path__
      regex: (.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      action: replace
      targetLabel: kubernetes_node
    - sourceLabels: [__meta_kubernetes_pod_ip]
      action: replace
      targetLabel: kubernetes_pod_ip
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: instance
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
      action: replace
      targetLabel: cluster
  namespaceSelector:
    matchNames:
      - tidb-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: tikv
```
