### ISSUE TITLE
Grafana shows "No data points"

### ISSUE THREAD

**Issue by danparisi** [pingcap/tidb-operator#2446]
I installed a tidb cluster and monitor via CRs, the cluster works fine but I see no data on grafana.

**What version of Kubernetes are you using?**
v1.14.6

**What version of TiDB Operator are you using?**
v1.1.0-rc.3

**What did you do?**
Here is my configuration, I started from here:
https://github.com/pingcap/tidb-operator/tree/master/examples/basic

**tidb-cluster.yaml**
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidb-cluster
spec:
  version: v3.0.13
  timezone: UTC
  pvReclaimPolicy: Retain
  pd:
    timezone: UTC
    baseImage: pingcap/pd
    replicas: 3
    limits:
      memory: 3Gi
    requests:
      memory: 1Gi
      storage: 2Gi
    storageClassName: ...
    config: {}
    affinity: ...

  tikv:
    timezone: UTC
    baseImage: pingcap/tikv
    replicas: 3
    limits:
      memory: 5Gi
    requests:
      memory: 1Gi
      storage: 15Gi
    storageClassName: ...
    maxFailoverCount: 0
    config: {}
    affinity: ...

  tidb:
    timezone: UTC
    baseImage: pingcap/tidb
    replicas: 2
    limits:
      memory: 3Gi
    requests:
      memory: 1Gi
    service:
      type: NodePort
    storageClassName: ...
    maxFailoverCount: 0
    config: {}
    affinity: ...

  pump:
    timezone: UTC
    baseImage: pingcap/tidb-binlog
    replicas: 3
    storageClassName: ...
    limits:
      memory: 2Gi
    requests:
      memory: 500Mi
      storage: 5Gi
    config:
      gc : 7
      heartbeat-interval : 2
      storage:
        stop-write-at-available-space : "512MB"
        sync-log : true
    affinity: ...
```

**tidb-monitor.yaml**
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: tidb-cluster
spec:
  clusters:
    - name: tidb-cluster
  storage: 5G
  persistent: true
  storageClassName: ...
  nodeSelector:
    zone: ...
  prometheus:
    baseImage: prom/prometheus
    version: v2.11.1
  grafana:
    baseImage: grafana/grafana
    version: 6.0.1
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v3.0.13
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
```

**What did you expect to see?**
Grafana panels filled up with cluster data

**What did you see instead?**
All the panel are empty with "No data points" message.
