### ISSUE TITLE
`pingcap.com/last-applied-configuration` annotation is synced to tc.spec.tidb.service.annotations

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2455]
## Bug Report

**What version of Kubernetes are you using?**

v1.12.8
**What version of TiDB Operator are you using?**

v1.1.0-rc.3
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Configure tc.spec.tidb.service.annotations as below:
```
    service:
      annotations:
        foo: bar
```
**What did you expect to see?**
The annotation should not be changed.
**What did you see instead?**
The `pingcap.com/last-applied-configuration` annotation is synced to tc.spec.tidb.service.annotations:
```
    service:
      annotations:
        foo: bar
        pingcap.com/last-applied-configuration: '{"ports":[{"name":"mysql-client","protocol":"TCP","port":4000,"targetPort":4000},{"name":"status","protocol":"TCP","port":10080,"targetPort":10080}],"selector":{"app.kubernetes.io/component":"tidb","app.kubernetes.io/instance":"test10","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"}}'
```
