### ISSUE TITLE
tombstone stores are shown in both the tiflash and tikv tombstone stores

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2458]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**
tikv tombstone stores are shown in the tikv status and tiflash tombstone stores are shown in the tiflash status
**What did you see instead?**
```
  tiflash:
    failureStores:
      "44":
        createdAt: "2020-05-11T08:01:49Z"
        podName: test30-tiflash-0
        storeID: "44"
      "46":
        createdAt: "2020-04-30T10:00:59Z"
        podName: test30-tiflash-1
        storeID: "46"
    image: pingcap/tiflash:v3.1.0-rc
    phase: Normal
    statefulSet:
      collisionCount: 0
      currentReplicas: 4
      currentRevision: test30-tiflash-64bfd84d45
      observedGeneration: 8
      readyReplicas: 3
      replicas: 4
      updateRevision: test30-tiflash-64bfd84d45
      updatedReplicas: 4
    stores:
      "44":
        id: "44"
        ip: test30-tiflash-0.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: "2020-05-11T07:22:14Z"
        lastTransitionTime: "2020-05-11T07:56:43Z"
        leaderCount: 0
        podName: test30-tiflash-0
        state: Down
      "46":
        id: "46"
        ip: test30-tiflash-1.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: "2020-05-13T08:03:59Z"
        lastTransitionTime: "2020-05-11T06:51:16Z"
        leaderCount: 0
        podName: test30-tiflash-1
        state: Up
      "47":
        id: "47"
        ip: test30-tiflash-2.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: "2020-05-13T08:03:55Z"
        lastTransitionTime: "2020-05-04T09:00:34Z"
        leaderCount: 0
        podName: test30-tiflash-2
        state: Up
      "48":
        id: "48"
        ip: test30-tiflash-3.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: "2020-05-13T08:03:56Z"
        lastTransitionTime: "2020-05-11T08:02:52Z"
        leaderCount: 0
        podName: test30-tiflash-3
        state: Up
    synced: true
    tombstoneStores:
      "45":
        id: "45"
        ip: test30-tiflash-1.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: null
        lastTransitionTime: null
        leaderCount: 0
        podName: test30-tiflash-1
        state: Tombstone
  tikv:
    image: pingcap/tikv:v3.1.0-rc
    phase: Normal
    statefulSet:
      collisionCount: 0
      currentReplicas: 1
      currentRevision: test30-tikv-d7b5bd7fc
      observedGeneration: 1
      readyReplicas: 1
      replicas: 1
      updateRevision: test30-tikv-d7b5bd7fc
      updatedReplicas: 1
    stores:
      "1":
        id: "1"
        ip: test30-tikv-0.test30-tikv-peer.test30.svc
        lastHeartbeatTime: "2020-05-13T08:03:54Z"
        lastTransitionTime: "2020-05-13T03:01:03Z"
        leaderCount: 21
        podName: test30-tikv-0
        state: Up
    synced: true
    tombstoneStores:
      "45":
        id: "45"
        ip: test30-tiflash-1.test30-tiflash-peer.test30.svc
        lastHeartbeatTime: null
        lastTransitionTime: null
        leaderCount: 0
        podName: test30-tiflash-1
        state: Tombstone
```
