### ISSUE TITLE
tombstone stores are shown in the failurestores

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2459]
## Bug Report

I deployed a TiDB cluster with TiFlash enabled on AWS with self-managed k8s cluster, each TiKV node has a tikv and tiflash pod. And then I've deleted one TiKV node, so tikv-1 and tiflash-0 becomes pending state. A new AWS ec2 instance was added after 10min. And then after 35min new tikv and tiflash was added and scheduled on the new ec2 instance.

Since I've used the advanced statefulset, by following the failover operation documentation, I've added the following annotations to `TidbCluster` object:

```yaml
annotations:
  tiflash.tidb.pingcap.com/delete-slots: '[0]'
  tikv.tidb.pingcap.com/delete-slots: '[1]'
```

The pending tikv was successfully removed, but tiflash was still there and the annotation was not propagated to tiflash AdvancedStatefulSet.

I also noted that the tombstone stores are in failurestore status:
![image](https://user-images.githubusercontent.com/7932127/81888729-88443c00-95d4-11ea-81c2-dff0ad0c807a.png)
