### ISSUE TITLE
Backup didn't store the table information.sql

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2522]
## Bug Report
TidbCluster version  v4.0.0-rc  ,tidb-backup-manager latest version.

1. insert data by blockwriter
2. delete blockwriter pod and use mysql client to check `block_writer` table.
3. use `backup` to the minio in the same k8s cluster.
4. download target the `tgz` file and untar it.
5. only `metadata` information in the `tgz` file, no table information sql file.

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v4.0.0-rc
  timezone: UTC
  pvReclaimPolicy: Delete
  tlsCluster:
    enabled: true
  pd:
    baseImage: pingcap/pd
    replicas: 1
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    requests:
      cpu: "1"
      storage: "1Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
    config: {}
    requests:
      cpu: "1"
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: blockwriter
  name: backup-blockwriter
spec:
  containers:
    - args:
        - --namespace=default
        - --cluster-name=backup
        - --database=sbtest
        - --password=
        - --table-num=1
        - --concurrency=1
        - --batch-size=1
        - --raw-size=1
      command:
        - /usr/local/bin/blockwriter
      image: hub.pingcap.net/tidb-operator-e2e/tidb-operator-e2e:9a13ab02d1bb4e121d65b4d2cf7f23a0d35806b2
      imagePullPolicy: IfNotPresent
      name: blockwriter
      resources: {}
```

```yaml
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: demo1-backup-ceph
#  namespace: test1
spec:
  backupType: full
  from:
    host: backup-tidb
    port: 4000
    user: root
    secretName: backup-demo1-tidb-secret
  s3:
    provider: ceph
    secretName: s3-secret
    endpoint: http://minio-service:9000
    bucket: local
    prefix: "2020-05-21T06:20:18Z"
  storageClassName: standard
  storageSize: 1Gi
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
    - name: minio
      image: minio/minio:RELEASE.2020-05-08T02-40-49Z
      imagePullPolicy: IfNotPresent
      args:
      - server
      - /data
      env:
      - name: MINIO_ACCESS_KEY
        value: "12345678"
      - name: MINIO_SECRET_KEY
        value: "12345678"
      readinessProbe:
        httpGet:
          path: /minio/health/ready
          port: 9000
        initialDelaySeconds: 120
        periodSeconds: 20
      livenessProbe:
        httpGet:
          path: /minio/health/live
          port: 9000
        initialDelaySeconds: 120
        periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
```

and the `tgz` file downloaded from minio only contains the metadata file:

![image](https://user-images.githubusercontent.com/13427348/82539581-442adb80-9b80-11ea-9219-d6532364aa3b.png)
