### ISSUE TITLE
TiDB Cluster deploy/upgrade failure when setting `pessimistic-txn` parameters for TiKV

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2592]
## Bug Report

**What version of Kubernetes are you using?**

1.12.10
**What version of TiDB Operator are you using?**

v1.1.0
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local-storage
**What's the status of the TiDB cluster pods?**

Running
**What did you do?**

1. Deploy TiDB Operator v1.1.0-rc.4 + TiDB v3.1.1
Configure below parameters for TiKV:
```
    config:
      log-level: info
      pessimistic-txn:
        wait-for-lock-timeout: 1000
        wake-up-delay-duration: 20
```
Upgrade TiDB Operator to v1.1.0, and then upgrade TiDB to v4.0, but upgrade failed with below logs:
```
E0529 09:24:40.252962       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1alpha1.TidbCluster: v1alpha1.TidbClusterList.Items: []v1alpha1.TidbCluster: v1alpha1.TidbCluster.Spec: v1alpha1.TidbClusterSpec.TiKV: v1alpha1.TiKVSpec.Config: v1alpha1.TiKVConfig.TiKVPessimisticTxn: v1alpha1.TiKVPessimisticTxn.WaitForLockTimeout: ReadString: expects " or n, but found 1, error found in #10 byte of ...|timeout":1000,"wake-|..., bigger context ...|info","pessimistic-txn":{"wait-for-lock-timeout":1000,"wake-up-delay-duration":20}},"image":"pingcap|...
```
2. Deploy TiDB Operator v1.1.0 + TiDB v3.1.1
Configure below parameters for TiKV:
```
    config:
      log-level: info
      pessimistic-txn:
        wait-for-lock-timeout: 1000
        wake-up-delay-duration: 20
```
TiDB Cluster cannot start up with below logs:
```
E0529 09:24:40.252962       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1alpha1.TidbCluster: v1alpha1.TidbClusterList.Items: []v1alpha1.TidbCluster: v1alpha1.TidbCluster.Spec: v1alpha1.TidbClusterSpec.TiKV: v1alpha1.TiKVSpec.Config: v1alpha1.TiKVConfig.TiKVPessimisticTxn: v1alpha1.TiKVPessimisticTxn.WaitForLockTimeout: ReadString: expects " or n, but found 1, error found in #10 byte of ...|timeout":1000,"wake-|..., bigger context ...|info","pessimistic-txn":{"wait-for-lock-timeout":1000,"wake-up-delay-duration":20}},"image":"pingcap|...
```
**What did you expect to see?**

**What did you see instead?**
