### ISSUE TITLE
Backup CR Does Not Seem To Be Working For Minio

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#2687]
## Bug Report

**What version of Kubernetes are you using?**
1.18

**What version of TiDB Operator are you using?**
1.1.0

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
NVME drive using microk8s hostpath-provisioner

**What's the status of the TiDB cluster pods?**
```
basic-monitor-78d585d996-2s8zs         3/3     Running     0          5h6m   10.218.142.106   srv1   <none>           <none>
cluster-1-discovery-84f9588644-tmf2w   1/1     Running     1          22h    10.218.228.147   srv1   <none>           <none>
cluster-1-pd-0                         1/1     Running     1          22h    10.218.77.37     srv1   <none>           <none>
cluster-1-tidb-0                       2/2     Running     0          22h    10.218.1.76      srv1   <none>           <none>
cluster-1-tidb-initializer-bnhvg       0/1     Completed   0          19h    10.218.87.82     srv1   <none>           <none>
cluster-1-tikv-0                       1/1     Running     5          22h    10.218.212.14    srv1   <none>           <none>
```

**What did you do?**
I applied this manifest:
```
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: cluster-1-backup-minio
  namespace: tidb
spec:
  from:
    host: cluster-1-tidb
    port: 4000
    user: root
    secretName: tidb-secret
  s3:
    provider: minio
    secretName: ceph-backup-secret
    endpoint: http://192.168.1.180:9000
    bucket: backup
```

**What did you expect to see?**
I expected to see the job start or at least an event or something related to the backup in the logs of one of the tidb pods.

**What did you see instead?**
When running 
```
kubectl get bk -n tidb -owide
```
I get this
```
NAME                     BACKUPPATH   BACKUPSIZE   COMMITTS   STARTED   COMPLETED   AGE
cluster-1-backup-minio                0                                             20m
```
and there doesn't to be any activity in any of the pods to do with this.

**Comment by sstubbs** [comment]
I didn't mention that I have also applied this
```
kubectl apply -n tidb -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/backup/backup-rbac.yaml
```

**Comment by DanielZhangQD** [comment]
@sstubbs could you please collect the logs of the backup Pod?

**Comment by Yisaer** [comment]
It seems the provider in your yaml is wrong. It should be like following:

```yaml
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: cluster-1-backup-minio
  namespace: tidb
spec:
  from:
    host: cluster-1-tidb
    port: 4000
    user: root
    secretName: tidb-secret
  s3:
    provider: ceph
    secretName: ceph-backup-secret
    endpoint: http://192.168.1.180:9000
    bucket: backup
```

Also, I think `ceph` here didn't make sense as it only represented for the common storage endpoint for the s3 interface.

**Comment by sstubbs** [comment]
It was my mistake. I didn't add a storageclass so backup pod was never being created.
```yaml
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: cluster-1-backup-minio
  namespace: tidb
spec:
  #serviceAccount: tidb-backup-manager
  storageClassName: microk8s-hostpath
  storageSize: 10Gi
  from:
    host: 10.152.183.169
    port: 4000
    user: root
    secretName: backup-user-secret
  s3:
    provider: minio
    secretName: backup-ceph-secret
    endpoint: http://192.168.1.180:9000
    bucket: backup
```
I have tried it with provider set to ceph and to minio and both seem to work fine. I have tried it with and without the service account commented here and it works so I guess it defaults to using that value anyway. Thanks for the help.
