### ISSUE TITLE
TidbMonitor scrapes across all namespaces unless namespace is set explicitly

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb-operator#2742]
TidbMonitor will scrape all pods across all namespaces unless you explicitly specify a namespace. This doesn't match the documentation here: https://pingcap.com/docs/tidb-in-kubernetes/stable/api-references/#tidbclusterref

Without a namespace:
```
    clusters:
    - name: mycluster
```

The kubernetes_sd_configs of the Prometheus config does not filter on the namespace:
```
  - role: pod
    namespaces:
      names:
      - ""
```

With a namespace:
```
    clusters:
    - namespace: mynamespace
       name: mycluster
```

The kubernetes_sd_configs of the Prometheus config filters on the namespace:
```
  - role: pod
    namespaces:
      names:
      - mynamespace
```
