### ISSUE TITLE
Istio mtls support

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#2904]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm using istio 1.6.4 and would like to enable mtls. I've create a tidb cluster with the following:
```
kubectl create namespace tidb && \
kubectl label namespace tidb istio-injection=enabled && \
kubectl apply -n tidb -f 11-tidb/cluster.yaml
```
The cluster.yaml looks like the following:
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: cluster-1
spec:
  version: v4.0.1
  timezone: UTC
  pvReclaimPolicy: Retain
  discovery: {}
  pd:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/pd
    replicas: 1 
    storageClassName: high-performance
    requests:
      storage: "250Gi"
    config: {}
  tikv:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tikv
    replicas: 1
    storageClassName: high-performance
    requests:
      storage: "250Gi"
    config: {}
  tidb:
    baseImage: registry.cn-beijing.aliyuncs.com/tidb/tidb
    replicas: 1
    service:
      type: ClusterIP
    config: {}
```
This works.
However once I enable mtls like the following:
```
kubectl apply -n tidb -f 11-tidb/peer-authentication.yaml
```
with this peer-authentication.yaml file: 
```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
```
I get this error when running sql statements against it:
```
ERROR 9001 (HY000): PD server timeout
```
It would be great if this could be supported.

**Describe the feature you'd like:**
Support for istio mtls

**Describe alternatives you've considered:**
I've considered using the native tls of tidb but would rather use istio mtls as I'm using it elsewhere and it theoretically should be more secure as it's checking the certificate from both sides.

**Comment by DanielZhangQD** [comment]
PD only supports one CN, not sure if istio supports setting the CN. cc @weekface

**Comment by sstubbs** [comment]
Thanks a lot. Sorry I missed this in the documentation.

**Comment by DanielZhangQD** [comment]
@sstubbs Did you get istio mtls work with TiDB?

**Comment by sstubbs** [comment]
I have tried everything I can think of with no luck unfortunately.

**Comment by sstubbs** [comment]
Not sure if this helps but when I install it with istio sidecar it works as the default is permissive. I use the following:
```
kubectl create namespace tidb-admin && \
kubectl label namespace tidb-admin istio-injection=enabled && \
helm install tidb-operator pingcap/tidb-operator --namespace=tidb-admin --version=1.1.2 -f 09-tidb-operator/values.yaml && \
kubectl get po -n tidb-admin -l app.kubernetes.io/name=tidb-operator
```
and
```
kubectl create namespace tidb && \
kubectl label namespace tidb istio-injection=enabled && \
kubectl apply -n tidb -f 10-tidb/cluster.yaml
```
Strangely kiali reports an error in this graph like the following even though it seems to work fine.
<img width="1440" alt="Screenshot 2020-07-27 at 19 46 22" src="https://user-images.githubusercontent.com/18033664/88580865-33955680-d044-11ea-99d5-dd5eacb28dcf.png">

If I apply this peerauthenitcal: 

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
```
to both namespaces of the operator and cluster. The graph doesn't report errors but it doesn't work anymore. I get the following:
<img width="1434" alt="Screenshot 2020-07-27 at 19 58 55" src="https://user-images.githubusercontent.com/18033664/88581115-9a1a7480-d044-11ea-9dd6-14d83afe9525.png">
