### ISSUE TITLE
Development - CR For Restore WIth BR Not Working With Minio

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#2996]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**
1.1.2

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
kind and kind local path provisioner

**What's the status of the TiDB cluster pods?**
```
NAME                                   READY   STATUS      RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
backup-cluster-1-backup-minio-b5gl8    0/1     Completed   0          8h    10.244.0.27   kind-control-plane   <none>           <none>
cluster-1-discovery-5674fb4784-q4ncs   1/1     Running     0          15h   10.244.0.12   kind-control-plane   <none>           <none>
cluster-1-pd-0                         1/1     Running     0          15h   10.244.0.14   kind-control-plane   <none>           <none>
cluster-1-tidb-0                       2/2     Running     0          15h   10.244.0.17   kind-control-plane   <none>           <none>
cluster-1-tidb-initializer-8nvcx       0/1     Completed   0          15h   10.244.0.18   kind-control-plane   <none>           <none>
cluster-1-tikv-0                       1/1     Running     0          15h   10.244.0.16   kind-control-plane   <none>           <none>
```

**What did you do?**
I setup a test cluster from https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md
I initialised it with a password and created a backup using dumpling to a minio bucket. This working well.
I used the following yaml to do that:
```
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: cluster-1-backup-minio
spec:
  serviceAccount: tidb-backup-manager
  storageSize: 10Gi
  from:
    host: cluster-1-tidb
    port: 4000
    user: root
    secretName: backup-user-secret
  s3:
    provider: minio
    secretName: backup-object-store-secret
    endpoint: https://my-minio-url
    bucket: backup
    prefix: one-time/cluster-1
```
I tested restore with lightning with the following:
```
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: cluster-1-restore-minio
spec:
  backupType: full
  serviceAccount: tidb-backup-manager
  storageSize: 10Gi
  to:
    host: cluster-1-tidb
    port: 4000
    user: root
    secretName: backup-user-secret
  s3:
    provider: minio
    secretName: backup-object-store-secret
    endpoint: https://my-minio-url
    path: backup/one-time/cluster-1/backup-2020-07-20T20:16:59Z.tgz
```
Which works perfectly. I then tested the same restore with BR with the following:
```
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: cluster-1-restore-minio
spec:
  br:
    cluster: cluster-1
    clusterNamespace: tidb
    # logLevel: info
    # statusAddr: ${status_addr}
    # concurrency: 4
    # rateLimit: 0
    # timeAgo: ${time}
    # checksum: true
    # sendCredToTikv: true
  to:
    host: cluster-1-tidb
    port: 4000
    user: root
    secretName: backup-user-secret
  s3:
    provider: minio
    secretName: backup-object-store-secret
    endpoint: https://my-minio-url
    path: backup/one-time/cluster-1/backup-2020-07-20T20:16:59Z.tgz
```
I have tried different settings like adding the service account I did for lightning to this manifest but it still doesn't work.

**What did you expect to see?**
tables restored

**What did you see instead?**
No restore job starts
