### ISSUE TITLE
The `Env` settings are ignored for the Grafana container in the TidbMonitor CR

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3235]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Set envs as below:
```
kubectl get tidbmonitor/tidb -o yaml
...
  grafana:
    baseImage: grafana/grafana
    envs:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
      GF_SERVER_DOMAIN: tidb.co
      GF_SERVER_ROOT_URL: 'grafana'
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
```
**What did you expect to see?**
The envs are shown in the Grafana container.
**What did you see instead?**
They are ignored.
