### ISSUE TITLE
support `--selector <label expression>` flag for multiple operators in one k8s cluster

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb-operator#3243]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This solves a few issues:
* We want to canary new versions of an operator within a single k8s cluster
* We also sometimes need to run a different operator for a new version of tidb we're testing
* We might want to try running a single operator per cluster inside the same namespace to be able to simply fence off traffic outside the single namespace

This flag would support all these use cases.

**Describe the feature you'd like:**

Add a flag to the operator like this `--selector <label expression>` where the label expression is key value pairs of labels and values. When the operator receives notifications for changes from the CRDs it monitors it will ignore CRDs that doesn't match the label expression.

For example.
Two operators:
A
`--selector operator=global`
B
`--selector operator=canary`

Two tidbclusters:
A
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  labels:
    operator: global
...
```
B
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  labels:
    operator: canary
...
```

Operator A would ignore tidbcluster B and operator B would ignore tidbcluster A.

**Describe alternatives you've considered:**

The alternative is to run operators per namespace and somehow scope the subscription via RBAC. (Not sure if that is possible but seems plausible.)

**Teachability, Documentation, Adoption, Migration Strategy:**

There is plenty of similar label selectors used in k8s so this would be familiar to users.
