### ISSUE TITLE
tiflash pods haven`t been deleted after scale down

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb-operator#3273]
## Bug Report

**What version of Kubernetes are you using?**
1.16.4

**What version of TiDB Operator are you using?**
1.1.3

**What did you do?**
1.create tidb cluster use 
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidbtest3
spec:
  annotations:
    prometheus.io/scheme: http
  configUpdateStrategy: RollingUpdate
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: 
  - name: tidbtest3-imagepull-secret
  schedulerName: tidb-scheduler
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
    service:
      type: ClusterIP
  tidb:
    baseImage: pingcap/tidb
    config:
      log:
        file:
          max-backups: 3
        level: info
    maxFailoverCount: 3
    replicas: 2
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    separateSlowLog: true
    service:
      type: ClusterIP 
    slowLogTailer:
      image: pingcap/busybox:1.31.1
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tikv:
    baseImage: pingcap/tikv
    config:
      log-level: info
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 3
    replicas: 1
    limits:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClaims:
    - resources:
        limits:
          storage: 20Gi
        requests:
          storage: 20Gi
      storageClassName: default
  timezone: UTC
  version: v4.0.3
```
upgrade tidb cluster use :
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidbtest3
spec:
  annotations:
    prometheus.io/scheme: http
  configUpdateStrategy: RollingUpdate
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: 
  - name: tidbtest3-imagepull-secret
  schedulerName: tidb-scheduler
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
    service:
      type: ClusterIP
  tidb:
    baseImage: pingcap/tidb
    config:
      log:
        file:
          max-backups: 3
        level: info
    maxFailoverCount: 3
    replicas: 2
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    separateSlowLog: true
    service:
      type: ClusterIP 
    slowLogTailer:
      image: pingcap/busybox:1.31.1
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tikv:
    baseImage: pingcap/tikv
    config:
      log-level: info
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
  timezone: UTC
  version: v4.0.3
```

**What did you expect to see?**
tiflash pods should be deleted
**What did you see instead?**
tiflash still there

**Comment by mikechengwei** [comment]
I think you just need to modify the `replica` field of tiflash spec ,if you change to nil , operator will skip update tiflash sts.

**Comment by DanielZhangQD** [comment]
> I think you just need to modify the `replica` field of tiflash spec to zero ,if you set tiflash to nil , operator will skip update tiflash sts.

@mikechengwei is correct.
@zgcbj We will update docs to make it clear how to remove the TiFlash resources.

**Comment by zgcbj** [comment]
> > I think you just need to modify the `replica` field of tiflash spec to zero ,if you set tiflash to nil , operator will skip update tiflash sts.
> 
> @mikechengwei is correct.
> @zgcbj We will update docs to make it clear how to remove the TiFlash resources.

I konw modify replica can delete tiflash.
Create tc  without tiflash then scale up with tiflash、scale down use yaml without tiflash, after these option,  yaml became same as initial, resource should also same as initial, operator should not ignore it.

**Comment by zgcbj** [comment]
yaml1:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidbtest3
spec:
  annotations:
    prometheus.io/scheme: http
  configUpdateStrategy: RollingUpdate
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: 
  - name: tidbtest3-imagepull-secret
  schedulerName: tidb-scheduler
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
    service:
      type: ClusterIP
  tidb:
    baseImage: pingcap/tidb
    config:
      log:
        file:
          max-backups: 3
        level: info
    maxFailoverCount: 3
    replicas: 2
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    separateSlowLog: true
    service:
      type: ClusterIP 
    slowLogTailer:
      image: pingcap/busybox:1.31.1
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tikv:
    baseImage: pingcap/tikv
    config:
      log-level: info
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
  timezone: UTC
  version: v4.0.3
```

yaml2:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tidbtest3
spec:
  annotations:
    prometheus.io/scheme: http
  configUpdateStrategy: RollingUpdate
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  imagePullSecrets: 
  - name: tidbtest3-imagepull-secret
  schedulerName: tidb-scheduler
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
    service:
      type: ClusterIP
  tidb:
    baseImage: pingcap/tidb
    config:
      log:
        file:
          max-backups: 3
        level: info
    maxFailoverCount: 3
    replicas: 2
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    separateSlowLog: true
    service:
      type: ClusterIP 
    slowLogTailer:
      image: pingcap/busybox:1.31.1
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tikv:
    baseImage: pingcap/tikv
    config:
      log-level: info
    maxFailoverCount: 3
    replicas: 3
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClassName: default
  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 3
    replicas: 1
    limits:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    requests:
      cpu: 4000m
      memory: 4Gi
      storage: 20Gi
    storageClaims:
    - resources:
        limits:
          storage: 20Gi
        requests:
          storage: 20Gi
      storageClassName: default
  timezone: UTC
  version: v4.0.3
```

create tc use yaml1 --> upgrade tc use yaml2 --> upgrade tc use yaml1     after this, yaml are same, pods should also same as init.
