### ISSUE TITLE
fail to generate the desired config for pump with float type config item

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-operator#3303]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

2ec8dfbf05fbb3513aea878ce4c2c13bf64a97b2  at master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

`kubectl apply -f tidb-cluster.yaml`
<details><summary>CLICK ME for tidb-cluster.yaml</summary>

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v4.0.6
  timezone: UTC
  pvReclaimPolicy: Delete
  discovery: {}
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: pingcap/pd
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "2MB"
  tidb:
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
    config:
      token-limit: 202
      max-server-connections: 51
  pump:
    baseImage: pingcap/tidb-binlog
    replicas: 1
    # storageClassName: local-storage
    requests:
      storage: 20Gi
    # schedulerName: default-scheduler
    config:
      gc: 7
      storage:
        kv:
          compaction-total-size-multiplier: 8.0


  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 3
    replicas: 1
    storageClaims:
      - resources:
          requests:
            storage: 1Gi
        # storageClassName: local-storage
    # requests:
    #   storage: "1Gi"
    config: {}
```
</details>
note for the `compaction-total-size-multiplier: 8.0` part

**What did you expect to see?**

all service works normal.
`compaction-total-size-multiplier` is set as 8.0 for pump.

**What did you see instead?**

pump crash
```
basic-json-pump-0                       0/1     CrashLoopBackOff   20         80m
```

This is caused by the the generated toml format config is not expected for pump.
`compaction-total-size-multiplier` must be a float type, and "8" is not a valid float value as toml spec.

```
➜  tidb-operator git:(master) ✗ kubectl logs  basic-pump-0
[2020/09/23 03:54:37.769 +00:00] [FATAL] [main.go:41] ["verifying flags failed. See 'pump --help'."] [error="toml: cannot load TOML value of type int64 into a Go float"]
```

```
➜  tidb-operator git:(master) ✗ kubectl describe cm basic-pump-6463376
Name:         basic-pump-6463376
Namespace:    default
Labels:       app.kubernetes.io/component=pump
              app.kubernetes.io/instance=basic
              app.kubernetes.io/managed-by=tidb-operator
              app.kubernetes.io/name=tidb-cluster
Annotations:  <none>

Data
====
pump-config:
----
gc = 7

[storage]
  [storage.kv]
    compaction-total-size-multiplier = 8

Events:  <none>
```

note `"compaction-total-size-multiplier":8`  
```
➜  tidb-operator git:(master) ✗  kubectl get tc basic -o yaml | more
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pingcap.com/v1alpha1","kind":"TidbCluster","metadata":{"annotations":{},"name":"basic","namespace":"default"},"spec":{"configUpdateStrategy":"RollingUpdate","discovery":{},"pd":{"baseImage":"pingcap/pd","config":{},"replicas":1,"requests":{"storage":"1Gi"}},"pump":{"baseImage":"pingcap/tidb-binlog","config":{"gc":7,"storage":{"kv":{"compaction-total-size-multiplier":8}}},"replicas":1,"requests":{"storage":"20Gi"}},"pvReclaimPolicy":"Delete","tidb":{"baseImage":"pingcap/tidb","config":{"max-server-connections":51,"token-limit":202},"replicas":1,"service":{"type":"ClusterIP"}},"tiflash":{"baseImage":"pingcap/tiflash","config":{},"maxFailoverCount":3,"replicas":1,"storageClaims":[{"resources":{"requests":{"storage":"1Gi"}}}]},"tikv":{"baseImage":"pingcap/tikv","config":{"storage":{"reserve-space":"2MB"}},"replicas":1,"requests":{"storage":"1Gi"}},"timezone":"UTC","version":"v4.0.6"}}
  creationTimestamp: "2020-09-22T16:12:32Z"
  generation: 387
```
pump uses the `GenericConfig` with no schema, so all float type will be no way to specified the desired value with the decimal part is zero.
but for all the integer type pump want, it's ok to specified a value with decimal part is zero, like `gc: 7.0`
https://github.com/pingcap/tidb-operator/blob/18703b979f22e2a1a29a817d2b81727896b7474d/pkg/apis/pingcap/v1alpha1/types.go#L630
