### ISSUE TITLE
tikv node storage class is unexcepted

### ISSUE THREAD

**Issue by CheneyDing** [pingcap/tidb-operator#3422]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**
```
TiDB Operator Version: version.Info{GitVersion:"v1.1.0-beta.1.656+b512f4bec00da7-dirty", GitCommit:"b512f4bec00da7c6cea9fe840853e9e6767c16af", GitTreeState:"dirty", BuildDate:"2020-10-21T07:14:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
```
NAME                          PROVISIONER                    AGE
local-storage                 kubernetes.io/no-provisioner   552d
nvme-disks                    kubernetes.io/no-provisioner   552d
shared-nvme-disks (default)   kubernetes.io/no-provisioner   552d
```
```
NAME                          STATUS   VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS        AGE
pd-st-2-pd-0                  Bound    local-pv-3dd44678   3667Gi     RWO            shared-nvme-disks   2d2h
tikv-auto-65d65769bf-tikv-0   Bound    local-pv-431fec5e   3667Gi     RWO            nvme-disks          139m
tikv-st-2-tikv-0              Bound    local-pv-2d1112aa   3667Gi     RWO            nvme-disks          2d2h
tikv-st-2-tikv-1              Bound    local-pv-ad1238d1   3667Gi     RWO            nvme-disks          2d2h
tikv-st-2-tikv-2              Bound    local-pv-51963a0    3667Gi     RWO            nvme-disks          2d2h
```

**What's the status of the TiDB cluster pods?**

```
NAME                               READY   STATUS    RESTARTS   AGE     IP               NODE          NOMINATED NODE
auto-65d65769bf-tikv-0             1/1     Running   0          140m    10.233.71.0      172.16.4.13   <none>
monitor-monitor-5cb5f58fb5-zdvkr   3/3     Running   0          10d     10.233.71.35     172.16.4.13   <none>
st-2-discovery-86b79bc87b-hczts    1/1     Running   0          30h     10.233.123.127   172.16.4.9    <none>
st-2-pd-0                          1/1     Running   2          2d2h    10.233.110.118   172.16.4.19   <none>
st-2-tidb-0                        2/2     Running   0          2d2h    10.233.107.196   172.16.4.14   <none>
st-2-tidb-1                        2/2     Running   0          2d2h    10.233.71.145    172.16.4.10   <none>
st-2-tidb-2                        2/2     Running   0          2d2h    10.233.120.162   172.16.4.22   <none>
st-2-tidb-3                        2/2     Running   0          2d2h    10.233.110.91    172.16.4.19   <none>
st-2-tidb-4                        2/2     Running   0          2d2h    10.233.120.32    172.16.4.25   <none>
st-2-tikv-0                        1/1     Running   0          3h47m   10.233.71.93     172.16.4.8    <none>
st-2-tikv-1                        1/1     Running   0          3h48m   10.233.71.57     172.16.4.13   <none>
st-2-tikv-2                        1/1     Running   0          3h50m   10.233.65.175    172.16.4.17   <none>
tidb-bench-0                       1/1     Running   0          7d1h    10.233.76.181    172.16.4.6    <none>
tidb-bench-1                       1/1     Running   0          7d1h    10.233.109.157   172.16.4.12   <none>
```

**What did you do?**
apply tidb-cluster.yaml

```
  tikv:
    baseImage: hub.pingcap.net/csn/tikv
    #baseImage: hub.pingcap.net/pingcap/tikv
    #baseImage: hub.pingcap.net/lhy1024/elastic
    config:
      log-level: info
      raftstore:
        raftdb-path: /var/lib/tikv/raft
      readpool:
        storage:
          use-unified-pool: false
          normal-concurrency: 64
      server:
        grpc-concurrency: 32
      status-addr: 0.0.0.0:20180
      storage:
        block-cache:
          capacity: 2GB
          shared: true
      rocksdb:
        defaultcf:
          disable-auto-compactions: false
      gc:
        enable-compaction-filter: true
        compaction-filter-skip-version-check: true
    limits:
      cpu: 8000m
      memory: 4Gi
      storage: 1000Gi
    replicas: 3
    requests:
      cpu: 8000m
      memory: 4Gi
      storage: 1000Gi
    storageClassName: nvme-disks
    #version: master-4761287
    #version: master-9a81ea6
    version: master-f94ed51
    #version: release-4.0.0-rc.1-a819792
    #version: tikv-a746e09
```

**What did you expect to see?**
all tikv nodes use nvme-disks

**What did you see instead?**
one tikv node (tikv 1) use shared-nvme-disks
![image](https://user-images.githubusercontent.com/24471884/96879268-6c5f9300-14ae-11eb-9d45-51b470b191c6.png)
![image](https://user-images.githubusercontent.com/24471884/96879317-7d100900-14ae-11eb-815a-7813a1004a0a.png)
