### ISSUE TITLE
more friendly hint if the yaml format is not as expect

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-operator#3468]
## Feature Request

**Is your feature request related to a problem? Please describe:**

apply this tidbmonitor success
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
  - name: basic-ym
  prometheus:
    baseImage: prom/prometheus
    version: v2.18.1
  grafana:
    baseImage: grafana/grafana
    version: 6.1.7
    envs: df
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v4.0.0
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
```

note the `envs` must be a map and it failed to unmarshal
logs of controller:
![WeChatWorkScreenshot_89baec4f-158c-47a8-ba9b-e314d0f90a03](https://user-images.githubusercontent.com/1681864/98338523-4822bb00-2045-11eb-9579-43e60ebbeaed.png)

so the pods can't  create normal

**Describe the feature you'd like:**

failed to apply the invalid tidbmonitor yaml

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
