### ISSUE TITLE
Support thanos container in tidbmonitor

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#3553]
## Feature Request

**Is your feature request related to a problem?**
#3292
Multiple tidb cluster monitor data  aggregation question.

**Describe the feature you'd like:**
```
  thanos:
    baseImage: xxx-image
    version: v0.8.1
    objectStorageConfig:
      key: objectstorage.yaml
      name: xxx-secret.
```
```
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage-ck
  namespace: xxx
type: Opaque
stringData:
  objectstorage.yaml: |
    type: S3
    config:
      bucket: "xxxxx"
      endpoint: "xxxxx"
      region: ""
      access_key: "xxxxxx"
      insecure: true
      signature_version2: true
      secret_key: "xxx"
      put_user_metadata: {}
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 2m
      trace:
        enable: false
      part_size: 41943040
```

**Describe alternatives you've considered:**

1.  Support thanos sidecar container.
2. Support data sync to s3.
