### ISSUE TITLE
Add additionalPrinterColumns in TidbCluster CRD

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#358]
Starting with Kubernetes 1.11, CRD spec supports [`additionalPrinterColumns` definition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns), which can facilitate CRD viewing from kubectl.

This enhancement is not conflict with the CLI tool, while both boosting the user experience in command line.

**Comment by aylei** [comment]
A simple example
```yaml
  additionalPrinterColumns:
  - name: PD Ready
    type: integer
    description: The ready replicas number of PD cluster
    JSONPaht: .status.pd.statefulSet.readyReplicas
  - name: PD Desired
    type: integer
    description: The desired replicas number of PD cluster
    JSONPath: .spec.pd.replicas
```

I will open a PR to discuss which columns do we need.
