### ISSUE TITLE
TiDBServiceSpec support additional ServicePort

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb-operator#3596]
## Feature Request
TiDB Spec support AdditionalContainers, but [TiDBServiceSpec ](https://godoc.org/github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1#TiDBServiceSpec) doesn't support additional [ServicePort](https://godoc.org/k8s.io/api/core/v1#ServicePort).

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

For example, I add a health-checker sidecar for tidb pod. I'd like to add ServicePort for tidb Service.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: External
  labels:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: db
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/used-by: end-user
  name: db-tidb
  namespace: tidb
spec:
  clusterIP: 100.65.245.103
  externalTrafficPolicy: Local
  healthCheckNodePort: 32123
  ports:
  - name: mysql-client
    nodePort: 30511
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: status
    nodePort: 31362
    port: 10080
    protocol: TCP
    targetPort: 10080
  - name: health-checker
    nodePort: 32402
    port: 8080
    protocol: TCP
    targetPort: 8080
```
We could add a AdditionalPorts field of []ServicePort type for TiDBServiceSpec.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
