### ISSUE TITLE
Failed to use storageVolume to mount log for `TiKV`

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#3627]
## Bug Report

Failed to use storageVolume to mount log for `TiKV` while PD and TIDB can.

**What version of TiDB Operator are you using?**

master version

**What did you do?**

Deploy following tc:

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test
  namespace: gaosong
spec:
  version: latest
  timezone: UTC
  enableTLSCluster: false
  pvReclaimPolicy: Delete
  enableAdvertiseAddress: true
  autoFailover: false
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: hub.pingcap.net/csn/pd
    version: 4.0.8-775b6a5
    replicas: 1
    requests:
      storage: 10Gi
    service:
      type: NodePort
    storageClassName: shared-nvme-disks
    config:
      log:
        level: "info"
        file:
          filename: /var/log/pdlog/pd.log
      dashboard:
        enable-telemetry: false
        enable-experimental: true
    storageVolumes:
      - name: log
        storageClass: shared-nvme
        storageSize: "20Gi"
        mountPath: "/var/log/pdlog"
  tikv:
    env:
      - name: TEST_TIKV_TAGS
        value: "test_need_restart"
    baseImage: pingcap/tikv
    version: v4.0.8
    replicas: 1
    storageClassName: shared-nvme-disks
    maxFailoverCount: 0
    evictLeaderTimeout: 1h
    requests:
      storage: 10Gi
    config:
      rocksdb:
        max-background-jobs: 6
        max-sub-compactions: 3
      log-level: "info"
      log-file: "/var/log/tikvlog/tikv.log"
      status-addr: "0.0.0.0:20180"
      storage:
        block-cache:
          capacity: "18GB"
          shared: true
      raftstore:
        raft-max-inflight-msgs: 8912
        perf-level: 5
        hibernate-regions: false
      readpool:
        coprocessor:
          use-unifiled-pool: true
          high-concurrency: 8
          normal-concurrency: 8
          low-concurrency: 8
      gc:
        enable-compaction-filter: true
        compaction-filter-skip-version-check: true
    storageVolumes:
      - name: log
        storageSize: "20Gi"
        mountPath: "/var/log/tikvlog"
  tidb:
    baseImage: hub.pingcap.net/csn/tidb
    version: 4.0.9-8af4c30
    replicas: 1
    maxFailoverCount: 0
    enableAdvertiseAddress: true
    service:
      type: ClusterIP
    storageClassName: shared-nvme-disks
    config:
      token-limit: 1000000
      prepared-plan-cache:
        enabled: true
      experimental:
        allow-auto-random: true
      log:
        level: "info"
        file:
          filename: /var/log/tidblog/tidb.log
    storageVolumes:
      - name: log
        storageClass: shared-nvme
        storageSize: "20Gi"
        mountPath: "/var/log/tidblog"

```

**What did you expect to see?**

**What did you see instead?**

operator log:
```sh
E1218 09:51:41.899979       1 tidb_cluster_control.go:128] tidb cluster gaosong/test is not valid and must be fixed first, aggregated error: [spec.tikv.storageVolumes[0].name: Required value: name must not be empty, spec.tikv.storageVolumes[0].mountPath: Required value: mountPath must not be empty]
```
