### ISSUE TITLE
Cluster becomes inaccessible randomly

### ISSUE THREAD

**Issue by 4c74356b41** [pingcap/tidb-operator#3637]
## Bug Report

**What version of Kubernetes are you using?**
1.17.13, GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495"

**What version of TiDB Operator are you using?**
1.1.4 both operator and cluster charts

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
data storage class is used for tidb pods, its a custom class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data
parameters:
  kind: managed
  storageaccounttype: Premium_LRS
  cachingmode: None
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
```

**What's the status of the TiDB cluster pods?**
```
tidb-discovery-7c698ffb54-v7cpz      2/2     Running            0          14h    10.240.0.109    aks-data-12358757-vmss000000
tidb-pd-0                            2/2     Running            0          14h    10.240.3.196    aks-data-12358757-vmss000002
tidb-pd-1                            2/2     Running            0          3d2h   10.240.1.35     aks-data-12358757-vmss000001
tidb-pd-2                            2/2     Running            0          3d2h   10.240.0.67     aks-data-12358757-vmss000000
tidb-tidb-0                          3/3     Running            0          3d2h   10.240.13.106   aks-data-12358757-vmss000004
tidb-tidb-1                          3/3     Running            0          3d2h   10.240.12.242   aks-data-12358757-vmss000004
tidb-tikv-0                          2/2     Running            0          3d2h   10.240.13.20    aks-data-12358757-vmss000004
tidb-tikv-1                          2/2     Running            0          24h    10.240.5.207    aks-w4112aafa6dd-12358757-vmss000001
tidb-tikv-2                          2/2     Running            0          14h    10.240.3.69     aks-data-12358757-vmss000002
```

**What did you do?**
its a helmfile spec, but it maps pretty closely to original values file, so i dont think it makes sense to translate it
```
  - rbac:
      create: false
  - clusterName: tidb
  - enablePVReclaim: true
  - discovery:
      tolerations: {{- toYaml .Environment.Values.tolerations | nindent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: agentpool
                operator: NotIn
                values:
                - data
  - pd:
      storageClassName: data
      priorityClassName: nimbus-persistence-priority
      tolerations: {{- toYaml .Environment.Values.tolerations | nindent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: agentpool
                operator: In
                values:
                - data
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: pd
              topologyKey: kubernetes.io/hostname
              namespaces:
              - nimbus-{{ requiredEnv "RELEASE_NAME" }}
  - tikv:
      storageClassName: data
      priorityClassName: nimbus-persistence-priority
      tolerations: {{- toYaml .Environment.Values.tolerations | nindent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: agentpool
                operator: In
                values:
                - data
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: tikv
              topologyKey: kubernetes.io/hostname
              namespaces:
              - nimbus-{{ requiredEnv "RELEASE_NAME" }}
  - tidb:
      storageClassName: data
      priorityClassName: nimbus-persistence-priority
      tolerations: {{- toYaml .Environment.Values.tolerations | nindent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: agentpool
                operator: In
                values:
                - data
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: tidb
              topologyKey: agentpool
              namespaces:
              - nimbus-{{ requiredEnv "RELEASE_NAME" }}
  - monitor:
      create: false
  - binlog:
      pump:
        create: false
      drainer:
        create: false
  - scheduledBackup:
      create: false
  - importer:
      create: false
```

**What did you expect to see?**
A working cluster

**What did you see instead?**
A working cluster that something timesout for no apparent reason, most of the time all the pods are in a running state but mysql workbench or our applications just timeout to connect to it. we are using istio, but we dont modify traffic inside the cluster at all and tidb is the only misbehaving service

using something like:
```
kubectl get po -o name | grep tidb | xargs kubectl delete 
```
fixes the issue temporary (so deleting tidb pods, not tidb-operator pods)
