### ISSUE TITLE
Allow configuration about replication task in TiCDC Spec 

### ISSUE THREAD

**Issue by tfulcrand** [pingcap/tidb-operator#3751]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Currently when we setup TiCDC component in TidbCluster CR object, we have to wait the `Running` status of ticdc pods and connect to one of them to manage replication task. If we use some specific options we need to create a TOML configuration task file before creating the replication task. 
The drawbacks of this method are :
- configuration is only available in one ticdc pod  
- configuration is lost when the pod restarts (during an upgrade for example)

**Describe the feature you'd like:**
Find a way to extend the `config` section in TiCDC Spec that allow adding configuration about replication task and this configuration will be available for all ticdc pods and persistent to pods restarts.

**Describe alternatives you've considered:**
None

**Teachability, Documentation, Adoption, Migration Strategy:**
We need a new TidbCluster CR definition. Maybe something like this :

```
ticdc:
  ...
  config:
    # timezone: UTC
    # gcTTL: 86400
    # logLevel: info
    # logFile: /dev/stderr
    replicationTaskConfig:
      case-sensitive: "true"
      enable-old-value: "false"
      ...
```

After that, documentations should be provided on the usage of this feature.
