### ISSUE TITLE
Backup CR doesn't delete s3 data when cleanPolicy: Delete is set

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb-operator#3760]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**

master 9b6838c8

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

```
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  9d
```

**What's the status of the TiDB cluster pods?**

```
tctest-discovery-78775659c5-btzfl   1/1     Running   0          4h20m
tctest-monitor-7d9d8f49d6-ntknt     3/3     Running   6          28h
tctest-pd-0                         1/1     Running   3          28h
tctest-pd-1                         1/1     Running   3          28h
tctest-pd-2                         1/1     Running   2          28h
tctest-tidb-0                       2/2     Running   5          28h
tctest-tidb-1                       2/2     Running   5          28h
tctest-tikv-0                       1/1     Running   8          28h
tctest-tikv-1                       1/1     Running   6          28h
tctest-tikv-2                       1/1     Running   6          28h
```

**What did you do?**

deploy a Backup yaml and delete it

```yaml
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: demo1-backup-s3
  namespace: default
spec:
  cleanPolicy: Delete
  br:
    cluster: tctest
  s3:
    provider: aws
    bucket: test-lyl
    secretName: s3-secret
    region: us-west-2
    cluster: tctest
  storageClassName: standard
  storageSize: 1Gi
```

**What did you expect to see?**
when backup is deleted, data on s3 is deleted too

**What did you see instead?**
when backup is deleted, data on s3 remains
