### ISSUE TITLE
Config is incorrecty transformed from yaml to toml

### ISSUE THREAD

**Issue by jonas0616** [pingcap/tidb-operator#3825]
## Bug Report

**What version of Kubernetes are you using?**

v1.17.1

**What version of TiDB Operator are you using?**

v.1.1.11

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

topolvm

**What's the status of the TiDB cluster pods?**

Running

**What did you do?**

Using helm to update pd config in tidbcluster resource. The diffs are:
```diff
      config:
        dashboard:
          internal-proxy: true
        replication:
          location-labels:
          - region
          - zone
          - rack
          - host
+       schedule:
+         enable-cross-table-merge: true
```

**What did you expect to see?**
TiDB operator automatically transformed the pd config from yaml to toml. The transformation should be correct.

**What did you see instead?**
Only the **changed fields** are shown in toml-formatted pd config after applying tidbcluster resource. The **unchanged fields** are missing. As you could see in the following tidbcluster, the pd config contains only the `enalbe-cross-table-merge` field, which is added in this apply.

```yaml
   pd:
     baseImage: pingcap/pd
     config: |
        [schedule]
          enable-cross-table-merge = true
```

Currently, I have to workaround this issue by using toml-formatted in tidbcluster resource to prevent incorrect transformation.

**Comment by DanielZhangQD** [comment]
@jonas0616 You still use tidb-cluster chart to manage the TiDB cluster? As we have mentioned in the [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/notes-tidb-operator-v1.1#pingcap-no-longer-updates-or-maintains-tidb-cluster-chart), we do not use the tidb-cluster chart to manage the TiDB cluster since v1.1.0, could you please try to manage the cluster with the TidbCluster CR directly?

**Comment by jonas0616** [comment]
@DanielZhangQD I'm not using tidb-cluster chart. It's a helm chart created by myself, and it contains a tidbcluster CRD resource.

```yaml
 apiVersion: pingcap.com/v1alpha1
 kind: TidbCluster
 metadata:
   labels:
     app.kubernetes.io/managed-by: Helm
   name: test-tidb
 spec:
   pd:
     baseImage: pingcap/pd
     config:
       dashboard:
          internal-proxy: true
        replication:
          location-labels:
          - region
          - zone
          - rack
          - host
        schedule:
          enable-cross-table-merge: true
....
```
