### ISSUE TITLE
can prometheus of tidbMonitor support add some scrape_configs 

### ISSUE THREAD

**Issue by slow-zhang** [pingcap/tidb-operator#3927]
## Question

now we can use [externalConfigMap](https://github.com/pingcap/tidb-operator/tree/master/examples/monitor-with-externalConfigMap) replace Prometheus config. Is there a method we add some scrape_configs?

**Comment by DanielZhangQD** [comment]
@slow-zhang Do you mean to add some customized scrape_configs to the Prometheus jobs?
If yes, it's not supported yet.
Could you please describe your requirement in detail? Why do you need this and how would you use this?

**Comment by slow-zhang** [comment]
thanks @DanielZhangQD , I want to add a component to tidb monitor. It's not necessary to change all scrape_config

**Comment by DanielZhangQD** [comment]
@slow-zhang Could you please submit a proposal to describe how you would like to do this, e.g. how the API would be changed?

**Comment by slow-zhang** [comment]
here is the Prometheus config:

```yaml
global:
  # How frequently to scrape targets by default.
  [ scrape_interval: <duration> | default = 1m ]

  # How long until a scrape request times out.
  [ scrape_timeout: <duration> | default = 10s ]

  # How frequently to evaluate rules.
  [ evaluation_interval: <duration> | default = 1m ]

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    [ <labelname>: <labelvalue> ... ]

  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
  [ query_log_file: <string> ]

# Rule files specify a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  [ - <filepath_glob> ... ]

# A list of scrape configurations.
scrape_configs:
  [ - <scrape_config> ... ]

# Alerting specifies settings related to the Alertmanager.
alerting:
  alert_relabel_configs:
    [ - <relabel_config> ... ]
  alertmanagers:
    [ - <alertmanager_config> ... ]

# Settings related to the remote write feature.
remote_write:
  [ - <remote_write> ... ]

# Settings related to the remote read feature.
remote_read:
  [ - <remote_read> ... ]
```
in which I want to add some config to scrape_configs instead to replace all config


the api action may performe:
when i write 
```yaml
prometheus-config-addon:
   - scrape_configs:
       - config: |
       xxxxxx 
```

it will add the config xxxxxx to  scrape_configs
so Prometheus config may change to 

```yaml
# A list of scrape configurations.
scrape_configs:
  [ - <old scrape_config> ... ]
  xxxxxx
```
