### ISSUE TITLE
Support backup ttl time.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4086]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When we enable backup schedule every 5min, it will produce many backup .So we can support ttl in backup. We can clean up expired backup every 1h.

**Describe alternatives you've considered:**
```
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: basic-backup-nfs
  namespace: default
spec:
  ttl: "5m"
```
