### ISSUE TITLE
Does dm monitor must have to rely on a tidb cluster?

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4165]
## Bug Report

**What did you do?**
When i use tidbmonitor monitor a dm cluster,it need I have to start a tidb cluster.
Ref:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:
  clusters:
  - name: basic
  dm:
    clusters:
    - name: basic
    initializer:
      baseImage: pingcap/dm-monitor-initializer
      version: v2.0.6
  imagePullPolicy: IfNotPresent
```

**What did you expect to see?**
Don't rely on tidb cluster.
