### ISSUE TITLE
Rolling update is triggered after applying the latest CRD

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#4297]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy TiDB Operator v1.2.4 and a basic cluster:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v5.2.1
  timezone: UTC
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: pingcap/pd
    replicas: 1
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    requests:
      storage: "1Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
    config: {}
```

Upgrade to the latest Operator with the latest CRD
**What did you expect to see?**
Nothing happens to the Pods
**What did you see instead?**
The Pods are rolling updated.
