### ISSUE TITLE
One Pd Pod can't run.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4338]
## Bug Report

**What version of Kubernetes are you using?**
1.21.2

**What version of TiDB Operator are you using?**
master branch

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
Local kind environment.
```
# IT IS NOT SUITABLE FOR PRODUCTION USE.
# This YAML describes a basic TiDB cluster with minimum resource requirements,
# which should be able to run in any Kubernetes cluster with storage support.
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v5.2.1
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        # In basic examples, we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
    config: {}

```

**What's the status of the TiDB cluster pods?**
pd log:
<img width="725" alt="Screen Shot 2021-12-30 at 3 04 33 PM" src="https://user-images.githubusercontent.com/13257127/147729623-754f6477-e4e3-4d9f-9c51-9eb5f43cb9f7.png">
