### ISSUE TITLE
TidbInitializer support specifying tidb endpoint

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#4399]
## Feature Request

For a cluster enabling SEM ([Security Enhanced Mode](https://github.com/pingcap/tidb/blob/master/docs/design/2021-03-09-security-enhanced-mode.md#detailed-design)), the tidb-server have limited permission, if we want to do some initialization that beyond SEM tidb-servers permissions, we have two choices:

* Disable SEM first and then run initialization SQL statement and then restart tidb to enable SEM
* Run TidbInitializer via a SEM disabled tidb-server, after that shut down SEM disabled tidb-server

The first one need to rolling restart all tidb-servers which might take a long time. While with the second one, TidbInitializer currently only support finding tidb-server endpoint via TidbCluster, so it's impossible to do the initialization via TidbInitializer.

So I'd like to allow user specifying a tidb endpoint for TidbInitializer.

**Comment by mikechengwei** [comment]
```
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: initialize-demo
spec:
  image: tnir/mysqlclient
  imagePullPolicy: IfNotPresent
  cluster:
    name: initialize-demo
    host:
    port:
```
Do you me above example code?
