### ISSUE TITLE
pod template merge patch strategic

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4472]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I want to add `hostAliases` field to tidbmonitor pod , i find no ways.

**Describe the feature you'd like:**
We can add a pod template merge patch strategic.User can specify pod template like below:
```
spec:
  containers:
  - name: prometheus
    readinessProbe:
      failureThreshold: 500
 hostAliases:
 - hostnames:
    - test.prometheus.com
       ip: 10.96.223.84
```
Operator will merge user custom template and our template , ouput a merge template.
