### ISSUE TITLE
TiDB & TiFlash aren't connecting and replicating, but they are online.

### ISSUE THREAD

**Issue by clanstyles** [pingcap/tidb-operator#4503]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.3.0", GitCommit:"17b1e59a4d07b9d3bce32132ff21158d982225cd", GitTreeState:"clean", BuildDate:"2022-02-15T08:42:55Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
```
kubectl get pvc -n tidb-cluster
NAME                          STATUS   VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
data0-basic-tiflash-0         Bound    pvc-e88a8dd288434b0f   30Gi       RWO            linode-block-storage-retain   7d20h
data0-basic-tiflash-1         Bound    pvc-e61248726b11449b   30Gi       RWO            linode-block-storage-retain   3d
data0-basic-tiflash-2         Bound    pvc-90d812def6ff42f9   30Gi       RWO            linode-block-storage-retain   3d
pd-basic-pd-0                 Bound    pvc-5ce9e95ebe504ad8   30Gi       RWO            linode-block-storage-retain   7d20h
pd-basic-pd-1                 Bound    pvc-08b30ec907ae489e   30Gi       RWO            linode-block-storage-retain   3d
pd-basic-pd-2                 Bound    pvc-0dee9a140c1c4e9c   30Gi       RWO            linode-block-storage-retain   3d
tidbmonitor-basic-monitor-0   Bound    pvc-4459a7f6d803499e   10Gi       RWO            linode-block-storage-retain   7d20h
tikv-basic-tikv-0             Bound    pvc-8c49e52fe4aa4149   30Gi       RWO            linode-block-storage-retain   7d20h
tikv-basic-tikv-1             Bound    pvc-7876547009c64575   30Gi       RWO            linode-block-storage-retain   3d
tikv-basic-tikv-2             Bound    pvc-f9563ffbe918492f   30Gi       RWO            linode-block-storage-retain   3d
```

```
kubectl get sc
NAME                                    PROVISIONER               RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
linode-block-storage                    linodebs.csi.linode.com   Delete          Immediate           true                   7d22h
linode-block-storage-retain (default)   linodebs.csi.linode.com   Retain          Immediate           true                   7d22h
```
**What's the status of the TiDB cluster pods?**
```
kubectl get po -n tidb-cluster -o wide
NAME                               READY   STATUS    RESTARTS   AGE     IP          NODE                          NOMINATED NODE   READINESS GATES
basic-discovery-7785f58447-7wxmv   1/1     Running   0          7d6h    10.2.4.9    lke56525-88628-6244f8ade52b   <none>           <none>
basic-monitor-0                    4/4     Running   0          7d20h   10.2.3.3    lke56525-88628-6244f8adedf3   <none>           <none>
basic-pd-0                         1/1     Running   0          7d20h   10.2.4.2    lke56525-88628-6244f8ade52b   <none>           <none>
basic-pd-1                         1/1     Running   0          3d      10.2.3.33   lke56525-88628-6244f8adedf3   <none>           <none>
basic-pd-2                         1/1     Running   0          3d      10.2.5.24   lke56525-88628-6244f8add84b   <none>           <none>
basic-tidb-0                       2/2     Running   0          7d20h   10.2.5.2    lke56525-88628-6244f8add84b   <none>           <none>
basic-tidb-1                       2/2     Running   0          3d      10.2.4.22   lke56525-88628-6244f8ade52b   <none>           <none>
basic-tidb-2                       2/2     Running   0          3d      10.2.3.35   lke56525-88628-6244f8adedf3   <none>           <none>
basic-tiflash-0                    4/4     Running   0          7d20h   10.2.4.3    lke56525-88628-6244f8ade52b   <none>           <none>
basic-tiflash-1                    4/4     Running   0          3d      10.2.3.34   lke56525-88628-6244f8adedf3   <none>           <none>
basic-tiflash-2                    4/4     Running   0          3d      10.2.5.25   lke56525-88628-6244f8add84b   <none>           <none>
basic-tikv-0                       1/1     Running   0          7d20h   10.2.5.3    lke56525-88628-6244f8add84b   <none>           <none>
basic-tikv-1                       1/1     Running   0          3d      10.2.4.23   lke56525-88628-6244f8ade52b   <none>           <none>
basic-tikv-2                       1/1     Running   0          3d      10.2.3.36   lke56525-88628-6244f8adedf3   <none>           <none>
```

**What did you do?**
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v5.4.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: |
      [replication]
        enable-placement-rules = true
    maxFailoverCount: 0
    replicas: 3
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "30Gi"
      # cpu: 3000m
      # memory: 16Gi
    storageClassName: linode-block-storage-retain
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    # If only 1 TiKV is deployed, the TiKV region leader 
    # cannot be transferred during upgrade, so we have
    # to configure a short timeout
    evictLeaderTimeout: 1m
    replicas: 3
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "30Gi"
      # cpu: 2000m
      # memory: 12Gi
    storageClassName: linode-block-storage-retain
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        # In basic examples, we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tiflash:
    baseImage: pingcap/tiflash
    maxFailoverCount: 0
    replicas: 3
    storageClaims:
    - resources:
        requests:
          storage: 30Gi
      storageClassName: linode-block-storage-retain
        #   cpu: 3000m
        #   memory: 16Gi
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 1
    replicas: 3
    service:
      type: ClusterIP
    config: {}
```

**What did you expect to see?**

**What did you see instead?**

We are having an issue where tiflash and tidb aren't playing together. I provided our release YAML above, but it seems that they are crashing or failing to connect. But the tidb dashboard says they are all online.

![image](https://user-images.githubusercontent.com/643269/162312556-e6f5f298-5dc0-4728-94db-bba5af23e60e.png)
![image](https://user-images.githubusercontent.com/643269/162312679-6a2d9bff-5ed7-47ee-8148-0f04675aa3f2.png)
![image](https://user-images.githubusercontent.com/643269/162313600-c5c481f0-4ff9-452f-81c4-f62da2265cc6.png)

In the tiflash replicaion, it always stays at 0.

How would we go about debugging this further?
