### ISSUE TITLE
Persist the prometheus-rules directory in initialization configuration of TM

### ISSUE THREAD

**Issue by wxiaoke** [pingcap/tidb-operator#4510]
At present, the persistent storage of tm is the data directory in the prometheus container. If the rules of prometheus are manually changed, persistent storage cannot be performed. It is recommended to persist this directory as well.

**Comment by KanShiori** [comment]
WDYT @mikechengwei

**Comment by DanielZhangQD** [comment]
@wxiaoke Does https://docs.pingcap.com/tidb-in-kubernetes/dev/monitor-a-tidb-cluster#use-a-customized-configuration-file this works for you?

**Comment by wxiaoke** [comment]
NO，The follower step is working.
使用 pvc 持久化步骤更新：
1. 需要创建一个 pvc

```
 cat pvc1.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pro-rules
  namespace: tidb-cluster
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
2. 然后更改 tidb-monitor 配置

```
  additionalVolumes:
  - name: pro-rules
    persistentVolumeClaim:
      claimName: pro-rules
  prometheus:
    additionalVolumeMounts:
    - name: pro-rules
      mountPath: "/prometheus-rules/rules/"
```
3. 创建 tm 并观察挂载情况
![origin_img_v2_d799fdcc-d683-4326-9e60-0985f7b627ag](https://user-images.githubusercontent.com/38338933/184818503-ec8653af-1680-41c1-9f3f-eac7a5bb10d1.jpg)
