### ISSUE TITLE
tidb-operator should validate pd/tikv config 

### ISSUE THREAD

**Issue by Tema** [pingcap/tidb-operator#4532]
## Bug Report

**What version of Kubernetes are you using?**
v1.21.10-gke.2000

**What version of TiDB Operator are you using?**
v1.3.2

**What did you do?**
I've applied the following config.
```
kind: TidbCluster
spec:
  version: v5.4.0
  pd:
    baseImage: pingcap/pd
    config:
      schedule:
         leader-schedule-policy: "count"
```

**What did you expect to see?**
I expected to see operator to reject applying CR as `leader-schedule-policy` is not a valid parameter.

**What did you see instead?**
tidb-operator accepted invalid CR and generated the following config map:
```
data:
config-file: |
[schedule]

startup-script: |
...
```
