### ISSUE TITLE
tidb-pd pod stuck at pending status when install tidb-cluster with topologySpreadConstraints

### ISSUE THREAD

**Issue by therealqxing** [pingcap/tidb-operator#4535]
## Bug Report

**What version of Kubernetes are you using?**
v1.21.11

**What version of TiDB Operator are you using?**
v1.2.4

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local pv

**What's the status of the TiDB cluster pods?**
```
# kubectl -n component get pods | grep tidb
tidb-controller-manager-64bf546bdf-hhd5h        1/1     Running            0          44m
tidb-discovery-597586bcfd-x9nqw         0/1     Pending            0          19s
tidb-pd-0                               0/1     Pending            0          22s
tidb-tidb-initializer-xpmph             0/1     Init:0/1           0          22s
```

**What did you do?**
1.Add following values in values.yaml
```
pd:
  ......
  topologySpreadConstraints:
  - topologyKey: kubernetes.io/hostname

tikv:
  ......
  topologySpreadConstraints:
  - topologyKey: kubernetes.io/hostname

tidb:
  ......
  topologySpreadConstraints:
  - topologyKey: kubernetes.io/hostname
```
2.Add following fields in templates/tidb-cluster.yaml
```
......
pd:
      topologySpreadConstraints:
{{ toYaml .Values.pd.topologySpreadConstraints | indent 6 }}

tikv:
      topologySpreadConstraints:
{{ toYaml .Values.tikv.topologySpreadConstraints | indent 6 }}

tidb:
      topologySpreadConstraints:
{{ toYaml .Values.tidb.topologySpreadConstraints | indent 6 }}
```

3. Run `helm install tidb-cluster . `

**What did you expect to see?**
tidb pods running normally

**What did you see instead?**
tidb pd pod stuck at pending status, and tidb controller mannager logs:
```
......
E0527 05:28:12.259566       1 pd_member_manager.go:188] failed to sync TidbCluster: [component/tidb]'s status, error: Get http://tidb-pd.component:2379/pd/health: dial tcp 10.233.8.38:2379: connect: connection refused, service component/tidb-pd has no endpoints
E0527 05:28:12.259739       1 tidb_cluster_controller.go:126] TidbCluster: component/tidb, sync failed TidbCluster: component/tidb .Status.PD.Synced = false, can't failover, requeuing
```
