### ISSUE TITLE
TiKV running replicas is not math the number in TiDBCluster CRD.

### ISSUE THREAD

**Issue by jaggerwang** [pingcap/tidb-operator#4549]
## Bug Report

**What version of Kubernetes are you using?**
1.20

**What version of TiDB Operator are you using?**
1.2

**What's the status of the TiDB cluster pods?**
```
$ kubectl get po -n tidb-cluster -o wide
NAME                                 READY   STATUS    RESTARTS   AGE    IP             NODE                        NOMINATED NODE   READINESS GATES
basicai-discovery-5d7d4dc88b-lr5xv   1/1     Running   0          110m   10.101.3.86    cn-shanghai.192.168.3.71    <none>           <none>
basicai-monitor-0                    3/3     Running   0          40m    10.101.3.211   cn-shanghai.192.168.1.251   <none>           <none>
basicai-pd-0                         1/1     Running   0          110m   10.101.3.207   cn-shanghai.192.168.1.251   <none>           <none>
basicai-tidb-0                       2/2     Running   0          104m   10.101.3.88    cn-shanghai.192.168.3.71    <none>           <none>
basicai-tiflash-0                    4/4     Running   0          109m   10.101.3.141   cn-shanghai.192.168.2.250   <none>           <none>
basicai-tikv-0                       1/1     Running   0          105m   10.101.3.208   cn-shanghai.192.168.1.251   <none>           <none>
basicai-tikv-1                       1/1     Running   0          106m   10.101.3.143   cn-shanghai.192.168.2.250   <none>           <none>
basicai-tikv-2                       1/1     Running   0          107m   10.101.3.142   cn-shanghai.192.168.2.250   <none>           <none>
basicai-tikv-3                       1/1     Running   0          12m    10.101.3.89    cn-shanghai.192.168.3.71    <none>           <none>
```

**What did you do?**
I migrate a TiDBCluster from one node pool to another in Aliyun ACK, but two of three TiKV nodes scheduled to same host. So I tried to increase TiKV replicas to 4 and decrease to 3, but the running replicas is still 4.

TiDBCluster CRD:
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basicai
spec:
  version: v5.2.1
  nodeSelector:
    dedicated: infra
  pd:
    replicas: 1
    storageClassName: alicloud-disk-tidb-pd
    requests:
      storage: "20Gi"
  tidb:
    replicas: 1
    service:
      type: ClusterIP
  tikv:
    replicas: 3
    storageClassName: alicloud-disk-tidb-tikv
    requests:
      storage: "200Gi"
  tiflash:
    replicas: 1
    storageClaims:
      - resources:
          requests:
            storage: "200Gi"
        storageClassName: alicloud-disk-tidb-tiflash

```

![image](https://user-images.githubusercontent.com/1255011/172814046-a35ab07d-e909-4d0c-b265-feae1dc9f2bc.png)

![image](https://user-images.githubusercontent.com/1255011/172814117-9bbac4cc-d1bd-45a7-a716-1f029a640a34.png)
