### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference when pd is nil

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tidb-operator#4690]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{GitVersion:"v1.3.1-4+13be85ed473f31", GitCommit:"13be85ed473f31579a33e3b109408b7a6b8048b2", GitTreeState:"clean", BuildDate:"2022-03-04T02:40:25Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

```
NAME                                                       READY   STATUS    RESTARTS   AGE
diag-77d8667d6f-bmjtw                                      1/1     Running   1          32d
tidb-admission-webhook-7c6cddff69-nj7wx                    1/1     Running   1          143d
tidb-controller-manager-7d6ddb4f66-xsqln                   1/1     Running   15         278d
tidb-controller-manager-test-infra-only-7cc4886b6d-czjjv   1/1     Running   0          18d
tidb-controller-manager-utf-only-94b65d75d-dvz7v           1/1     Running   2          91d
```

**What did you do?**

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: cdc
  namespace: testbed-cdc-test
spec:
  acrossK8s: true
  cluster:
    name: upstream
  ticdc:
    baseImage: hub.pingcap.net/qa/ticdc
    config: |
      cluster-id = "efg"
      log-file = "/var/lib/ticdc/log/ticdc.log"
    limits:
      cpu: 4000m
      memory: 8Gi
    replicas: 1
    requests:
      cpu: 250m
      memory: 256Mi
    storageVolumes:
    - mountPath: /var/lib/ticdc/log
      name: log
      storageClassName: local-path
      storageSize: 10Gi
    - mountPath: /tmp
      name: data
      storageSize: 500Gi
  timezone: UTC
  version: master
```

**What did you expect to see?**

No error

**What did you see instead?**

```
E0905 13:13:25.413843       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 71282097 [running]:
k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1.1(0xc00173c840)
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/rest.go:233 +0xdf
panic(0x1ddb260, 0x3187b90)
	runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1/validation.ValidateUpdateTidbCluster(0xc001317080, 0xc001316580, 0xc001316580, 0x20a4301, 0xc001317080)
	github.com/pingcap/tidb-operator/pkg/apis@v1.3.1/pingcap/v1alpha1/validation/validation.go:511 +0x2c4
github.com/pingcap/tidb-operator/pkg/registry.TidbClusterStrategy.ValidateUpdate(0x23ef0e8, 0xc000052050, 0x23b5f20, 0xc001316580, 0x23b5f20, 0xc001317080, 0x0, 0x0, 0xc000b778c0)
	github.com/pingcap/tidb-operator/pkg/registry/tidbcluster_strategy.go:55 +0xae
github.com/pingcap/tidb-operator/pkg/webhook/strategy.(*StrategyAdmissionHook).Validate(0xc00000fc10, 0xc001252000, 0x0)
	github.com/pingcap/tidb-operator/pkg/webhook/strategy/webhook.go:82 +0x4ae
github.com/openshift/generic-admission-server/pkg/apiserver.validatingAdmissionHookV1Beta1Wrapper.Admission(...)
	github.com/openshift/generic-admission-server@v1.14.1-0.20210422140326-da96454c926d/pkg/apiserver/apiserver.go:340
github.com/openshift/generic-admission-server/pkg/registry/admissionreview.(*REST).Create(0xc000688428, 0x23ef158, 0xc0010f97d0, 0x23b6f60, 0xc0010f9980, 0x2193678, 0xc000205680, 0x0, 0x0, 0x0, ...)
	github.com/openshift/generic-admission-server@v1.14.1-0.20210422140326-da96454c926d/pkg/registry/admissionreview/admission_review.go:43 +0x4c
k8s.io/apiserver/pkg/endpoints/handlers.(*namedCreaterAdapter).Create(0xc0002deb10, 0x23ef158, 0xc0010f97d0, 0x0, 0x0, 0x23b6f60, 0xc0010f9980, 0x2193678, 0xc000205680, 0x63aaba, ...)
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/create.go:208 +0x7f
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.1(0x1e1f680, 0x0, 0x0, 0x0)
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/create.go:145 +0x13b
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.2(0xc00068d0e0, 0x7f508660ac48, 0xc0006c2a78, 0xc001241c00)
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/create.go:166 +0xe7
k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc00173c840, 0xc00173c4e0, 0xc00173c7e0, 0xc00173c5a0)
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/rest.go:241 +0x62
created by k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
	k8s.io/apiserver@v0.19.16/pkg/endpoints/handlers/rest.go:222 +0xd4
```
