### ISSUE TITLE
TiFlash re-scale from 0 stuck if with a less storage than previous

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tidb-operator#4843]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.4.0

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

in AWS EKS with EBS PV

**What's the status of the TiDB cluster pods?**

**What did you do?**

1. create a TiFlash with 1 replica and 110G storage and m6g.xlarge instance in AWS EKS
2. scale TiFlash to 0
3. scale TiFlash to 1 with 100G storage

**What did you expect to see?**

tc synced and the following tiflash status

```
      volumes:
        data0:
          boundCount: 1
          currentCapacity: 100Gi
          currentCount: 1
          currentStorageClass: tiflash-gp3-6000-625
          modifiedCapacity: 100Gi
          modifiedCount: 1
          modifiedStorageClass: tiflash-gp3-6000-625
          name: data0
          resizedCapacity: 100Gi
          resizedCount: 1
```

**What did you see instead?**

```
      volumes:
        data0:
          boundCount: 1
          currentCapacity: 110Gi
          currentCount: 1
          currentStorageClass: tiflash-gp3-6000-625
          modifiedCapacity: 100Gi
          modifiedCount: 0
          modifiedStorageClass: tiflash-gp3-6000-625
          name: data0
          resizedCapacity: 100Gi
          resizedCount: 0
```
