### ISSUE TITLE
TiKV and TiFlash miss lastTransitionTime for tombstoneStores in status

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tidb-operator#4854]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.4.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

scale in TiFlash.

**What did you expect to see?**

tombstoneStores have `lastTransitionTime`

**What did you see instead?**

```
    tombstoneStores:
      "6":
        id: "6"
        ip: db-tiflash-0.db-tiflash-peer.tidb-cluster.svc
        lastTransitionTime: null
        leaderCount: 0
        podName: db-tiflash-0
        state: Tombstone
```
