### ISSUE TITLE
Operator not update runing pods affinity by scaling tikv

### ISSUE THREAD

**Issue by taislapta** [pingcap/tidb-operator#4860]
## Bug Report

**What version of Kubernetes are you using?**
1.22.16 GKE

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.1.0-cache-with-deno-320-gb00ae5cc32ae2a", GitCommit:"b00ae5cc32ae2a2ac9b9603820dc0431834a4e84", GitTreeState:"clean", BuildDate:"2022-12-29T09:57:09Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
premium-rwo          pd.csi.storage.gke.io

**What's the status of the TiDB cluster pods?**
```
NAME                                 READY   STATUS    RESTARTS   AGE     IP             NODE                                                  NOMINATED NODE   READINESS GATES
testcluster-discovery-xxx9f54bb-q4wpl   1/1     Running   0          2d21h   10.113.2.192   gke-platform-testcluster-dev-gke-main-v1-xxx852ac-c4ki   <none>           <none>
testcluster-monitor-0                   4/4     Running   0          34d     10.113.4.143   gke-platform-testcluster-dev-gke-data-xxxc3d86-dxz8      <none>           <none>
testcluster-pd-0                        1/1     Running   0          2d21h   10.113.4.138   gke-platform-testcluster-dev-gke-data-xxxc3d86-dxz8      <none>           <none>
testcluster-pd-1                        1/1     Running   0          2d15h   10.113.1.160   gke-platform-testcluster-dev-gke-data-xxx4ebe7-9p63      <none>           <none>
testcluster-pd-2                        1/1     Running   0          2d21h   10.113.1.10    gke-platform-testcluster-dev-gke-data-xxx3457b-vgph      <none>           <none>
testcluster-ticdc-0                     1/1     Running   0          4d19h   10.113.2.216   gke-platform-testcluster-dev-gke-main-v1-xxx52ac-c4ki   <none>           <none>
testcluster-ticdc-1                     1/1     Running   0          2d15h   10.113.3.217   gke-platform-testcluster-dev-gke-main-v1-xxx3eb6b-sa3i   <none>           <none>
testcluster-ticdc-2                     1/1     Running   0          4d19h   10.113.0.137   gke-platform-testcluster-dev-gke-data-xxx3457b-d3hh      <none>           <none>
testcluster-tidb-0                      2/2     Running   0          2d15h   10.113.2.2     gke-platform-testcluster-dev-gke-data-xxx4ebe7-4s6s      <none>           <none>
testcluster-tidb-1                      2/2     Running   0          3d21h   10.113.4.134   gke-platform-testcluster-dev-gke-data-xxxc3d86-dxz8      <none>           <none>
testcluster-tidb-2                      2/2     Running   0          3d21h   10.113.0.132   gke-platform-testcluster-dev-gke-data-xxx3457b-d3hh      <none>           <none>
testcluster-tidb-3                      2/2     Running   0          3d21h   10.113.1.3     gke-platform-testcluster-dev-gke-data-xxx3457b-vgph      <none>           <none>
testcluster-tidb-4                      2/2     Running   0          3d21h   10.113.1.135   gke-platform-testcluster-dev-gke-data-xxx4ebe7-9p63      <none>           <none>
testcluster-tidb-5                      2/2     Running   0          3d21h   10.113.5.84    gke-platform-testcluster-dev-gke-data-xxxc3d86-8n4w      <none>           <none>
testcluster-tikv-0                      1/1     Running   0          2d15h   10.113.2.13    gke-platform-testcluster-dev-gke-data-xxx4ebe7-4s6s      <none>           <none>
testcluster-tikv-1                      1/1     Running   0          2d17h   10.113.4.144   gke-platform-testcluster-dev-gke-data-xxx3d86-dxz8      <none>           <none>
testcluster-tikv-2                      1/1     Running   0          2d17h   10.113.0.130   gke-platform-testcluster-dev-gke-data-xxx3457b-d3hh      <none>           <none>
testcluster-tikv-3                      0/1     Pending   0          2d15h   <none>         <none>                                                <none>           <none>
testcluster-tikv-4                      0/1     Pending   0          2d15h   <none>         <none>                                                <none>           <none>
testcluster-tikv-5                      0/1     Pending   0          2d15h   <none>         <none>                                                <none>           <none>
testcluster-tikv-6                      0/1     Pending   0          2d15h   <none>         <none>                                                <none>           <none>
ng-monitor-ng-monitoring-0           1/1     Running   0          34d     10.113.2.160   gke-platform-testcluster-dev-gke-main-v1-xxx852ac-c4ki   <none>           <none>

x6 data nodes; x2 nodes in one AZ 
```

**What did you do?**
```
    replicas: 6  # changed replicas from 3 -> 6
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    storageClassName: premium-rwo
    requests:
      memory: "4Gi"
      cpu: "900m"
      storage: "300Gi"
    limits:
      memory: "16Gi"
      cpu: "8000m"
    config: |
      log-level= "error"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - tikv
            topologyKey: kubernetes.io/hostname # changed from "topology.kubernetes.io/zone" -> "kubernetes.io/hostname"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: pool-type
                  operator: In
                  values:
                    - data
    topologySpreadConstraints:
      - topologyKey: "topology.kubernetes.io/zone"
```

**What did you expect to see?**
old pods start rolling restart with updated affinity  and new starting afterwards 

**What did you see instead?**
pods pending , because running exsisting tikv pods(0,1,2) has  old podAntiAffinity. and operator not update it. 
Event if you delete podAntiAffinity and update TidbCluster CR it still not reconcile old pods   

```
Warning  FailedScheduling   69s (x2 over 2m35s)  default-scheduler   0/12 nodes are available: 6 node(s) didn't match Pod's node affinity/selector, 6 node(s) didn't  satisfy existing pods anti-affinity rules.
```
