### ISSUE TITLE
Helm chart repo index source urls are using http schema (not https)

### ISSUE THREAD

**Issue by maeb** [pingcap/tidb-operator#4984]
## Bug Report
All the urls in the [helm chart index](https://charts.pingcap.org/index.yaml) are using http and not https schema.

**What version of Kubernetes are you using?**
v1.25.8

**What did you do?**
Tried to download a chart behind a proxy using `https_proxy=myproxy.example.test:port`.

**What did you expect to see?**
The listed schema was expected to be `https` for all urls.

**What did you see instead?**
Excerpt from the chart index:
```
 - apiVersion: v1
   ...
   name: tidb-backup
   sources:
   - https://github.com/pingcap/tidb-operator
   urls:
   - http://charts.pingcap.org/tidb-backup-v1.4.4.tgz   <-------------------
   version: v1.4.4
```
