### ISSUE TITLE
Modify tidb-cluster, unable to update pd, tikv

### ISSUE THREAD

**Issue by lizhifengones** [pingcap/tidb-operator#5184]
## Bug Report

**What version of Kubernetes are you using?**

1.16, 1.21

**What version of TiDB Operator are you using?**

pingcap/tidb-operator:v1.3.9

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local-path, ceph

**What's the status of the TiDB cluster pods?**

**What did you do?**

Use Kustomize to modify the kind: pd of tidbcluster, the number of copies of tikv replicas separately, and the update of pd and tikv cannot be monitored

```
# 0->1
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: advanced-tidb
spec:
  pd:
    replicas: 1
  tikv:
    replicas: 1
```

**What did you expect to see?**
```
Use Kustomize to modify the kind: pd of tidbcluster, replicas of tikv separately, listen to the update of pd and tikv, and perform rolling update of the corresponding sts
```

**What did you see instead?**
