### ISSUE TITLE
TidbCluster with .spec.acrossK8s cannot start

### ISSUE THREAD

**Issue by hidalgopl** [pingcap/tidb-operator#5231]
## Bug Report

**What version of Kubernetes are you using?**
v1.24

**What version of TiDB Operator are you using?**
`v1.5.0`

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**
pods are running, but TiDBCluster has status: `TiKVStoreNotUp`

**What did you do?**
I was trying to follow the multi-cluster tutorial: https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-cluster-across-multiple-kubernetes

I applied the following manifest:
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: foo
spec:
  version: v7.1.0
  timezone: UTC
  pvReclaimPolicy: Delete
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  clusterDomain: cluster.local
  acrossK8s: true
  discovery: {}
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 1
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 1
    requests:
      storage: "10Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
    config: {}
```

**What did you expect to see?**
I expected to see `TiDBCluster` getting status:
```yaml
Status:
  Cluster ID:  7264954738145913996
  Conditions:
    Last Transition Time:  2023-08-08T15:43:26Z
    Last Update Time:      2023-08-08T15:43:26Z
    Message:               TiDB cluster is fully up and running
```

**What did you see instead?**

```yaml
Status:
  Cluster ID:  7264954738145913996
  Conditions:
    Last Transition Time:  2023-08-08T14:14:16Z
    Last Update Time:      2023-08-08T15:30:07Z
    Message:               TiKV store(s) are not up
    Reason:                TiKVStoreNotUp
    Status:                False
    Type:                  Ready
```

I checked the `tikv` pod logs and it was stuck on:
```
tidb-cluster-leaf-tikv-0 tikv waiting for the verification of PD endpoints ...
```

**Fix**
I exec into the pod and tried to run the `wget` command from the startup script:
```
{{ define "AcrossK8sSubscript" }}
pd_url={{ .AcrossK8s.PDAddr }}
encoded_domain_url=$(echo $pd_url | base64 | tr "\n" " " | sed "s/ //g")
discovery_url={{ .AcrossK8s.DiscoveryAddr }}
until result=$(wget -qO- -T 3 http://${discovery_url}/verify/${encoded_domain_url} 2>/dev/null | sed 's/http:\/\///g'); do
    echo "waiting for the verification of PD endpoints ..."
    sleep $((RANDOM % 5))
done
{{- end }}
```
but wget is not present on the `pingcap/tikv` image! After I run `yum install wget`, the `tikv` pod started functioning normally.
Then, I noticed that now `tidb` pod is stuck on the same step. I exec into the pod, run `yum install wget` and everything start to work properly and the `TiDBCluster` transitioned into "Ready" condition.

I noticed that `curl` is installed on the `pingcap/tikv` & `pingcap/tidb` image. Maybe it can be used in the startup script instead of wget? I'm happy to file such PR.

Relevant startup script templates:
- https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/startscript/v2/tidb_start_script.go#L79
- https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/startscript/v2/tikv_start_script.go#L97
- https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/startscript/v1/template.go#L285
- https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/startscript/v1/template.go#L71
