### ISSUE TITLE
ArgoCD sync loops caused  by tikv config rewrite

### ISSUE THREAD

**Issue by adamtwiss** [pingcap/tidb-operator#5365]
## Bug Report

**What version of Kubernetes are you using?**
Server: 1.28.0
Client: 1.27.3

**What version of TiDB Operator are you using?**

```
TiDB Operator Version: version.Info{GitVersion:"v1.6.0-alpha.8", GitCommit:"707e8805b83d1dc0f036f3eceac70349a6111ab9", GitTreeState:"clean", BuildDate:"2023-09-02T00:08:15Z", GoVersion:"go1.19.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

ceph-block

**What's the status of the TiDB cluster pods?**

All healthy

**What did you do?**

Use the example configs e.g. https://github.com/pingcap/tidb-operator/blob/master/examples/basic/tidb-cluster.yaml with ArgoCD.

**What did you expect to see?**

That Argo gets into a consistent state where kubernetes state matches the intended state.

**What did you see instead?**

Argo infinite sync loops, caused by config rewriting in the opreator. 
Specifically Something in the operator (or deeper in the stack) rewrites the TidbCluster.spec.tikv.config from (in the case of that example) from:

```
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        # In basic examples, we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files: 256
      raftdb:
        max-open-files: 256
```
To: 
```
    config: |
      [raftdb]
        max-open-files = 256

      [rocksdb]
        max-open-files = 256

      [storage]
        reserve-space = "0MB"
```
This results in Argo saying 'oh there's a diff here, let me sync again' and Argo gets stuck in a Sync loop.  You can work around this by matching character for character (no stray spaces or newlines) the intended state in your source file, but this is uggly

For anyone using declarative gitops with something like Argo, you cannot change the state.  I can make Argo ignore all diffs in the config section, but that would make it then unconfigurable (e.g. you coudln't make a legitimate change).

The overall impact is that TiDB operator doesn't really work in a declarative git-ops driven workflow.
        
Simplest steps to recreate (without Argo):
* kubectl apply -f examples/basic/tidb-cluster.yaml
* kubectl get { object created above }

The object is materially different from what was applied in the spec.tikv.config section.

Suggested fix. Any config rewriting to generate the '.ini' format .tikv/config file shouldn't get persisted back to the TIdbCluster object.

Please reach out if you need more info.
