### ISSUE TITLE
TiDB Cluster Does Not Survive K8s Upgrade (EKS) or Nodegroup Upgrade

### ISSUE THREAD

**Issue by towens** [pingcap/tidb-operator#5644]
## Bug Report

**What version of Kubernetes are you using?**
v1.24 - v1.26

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.5.3", GitCommit:"2c9e4dad0abaa4400afdef9ceff3084e71510ecb", GitTreeState:"clean", BuildDate:"2024-04-18T03:43:46Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/arm64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
Proper storage classes were created and being used

**What's the status of the TiDB cluster pods?**
Running as we have repeatedly set the tidb cluster to a zero state by deleting it, dropping the pvc's and pv's and recreating the cluster

**What did you do?**
Upgrade k8s (EKS) and/or an EKS nodegroup

**What did you expect to see?**
Pods running

**What did you see instead?**
Pods pending, typical volume conflicts.

This was all solved years ago with topologySpreadConstraints. Unfortunately the tidb-operator doesn't implement the full topologySpreadConstraints spec.

tidb-operators users (at minimum) need:
```
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: "intended-resource"
```

Neither the basic or advanced examples survive upgrades. We are open to the idea something simple was missed. TiDB is the only offering we have issues with.

Does there need to be a PR for full the spec of topologySpreadConstraints?
Is this obvious to folks working on this project but a docs PR is needed for those not living that context?

Thanks.
