### ISSUE TITLE
I would like to add allowPrivilegeEscalation

### ISSUE THREAD

**Issue by JacksonChen63** [pingcap/tidb-operator#5961]
Env: GKE 1.30.5-gke.1443001
TiDB: 8.4.0

I have try to modify the CRD tidbdashboards.pingcap.com able to add allowPrivilegeEscalation to Kind:TidbDashboard. After that I could add it and apply successful but still could exec pod tidbdashboard and execute su - .

Here is my tidb-dashboard and crd tidbdashboards.pingcap.com configuration.

[tidb.zip](https://github.com/user-attachments/files/17972626/tidb.zip)

**Comment by csuzhangxc** [comment]
what's the result of `su -`, does it succeed or ask you to enter the password?

**Comment by JacksonChen63** [comment]
@csuzhangxc , it ask me enter the password

**Comment by csuzhangxc** [comment]
I tried to create a Pod directly with the following YAML, and it asked me to enter the password. So if we want to fully disable this, we may need to rebuild the image.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: my-container
      image: pingcap/tidb-dashboard:v8.4.0
      command: ["sh", "-c", "sleep 1h"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 101
```
