### ISSUE TITLE
expose tikv metrics port in tikv peer service

### ISSUE THREAD

**Issue by plevart** [pingcap/tidb-operator#5970]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm exposing metrics to an existent prometheus-like scraping. I'm using VictoriaMetrics Operator with VMScrapeConfig CRs for that (similar to Prometheus Operator ServiceMonitor CRs). I'm using the *-peer services created as a result of TidbCluster RC since they are headless and so the VMScrapeConfig actually scrapes the underlying pods individually and doesn't load-balance scrape requests in case normal ClusterIP was used.

All -peer services created for pd, tidb and tiflash include ports where /metrics HTTP endpoints reside. Except the tikv-peer service. It is also not possible to add additionalPorts or similar to current TidbCluster CR to achieve that.

**Describe the feature you'd like:**
I would like that the metrics port of tikv peer service would be exposed by default or at least through the additionalPorts in the TidbCluster CR.

**Describe alternatives you've considered:**
Currently I'm manually deploying an additional Service with metrics port (20180). But I'd like this to be part of TidbCluster deployment like with other services (pd, tidb, tiflash).

I'm using TiDB Operator 1.6.0 with TiDB 8.1.1

Regards, Peter

**Comment by csuzhangxc** [comment]
The better way is scraping metrics from pods directly instead of from a (headless) service.
TiKV's headless service is used to communicate with PD

**Comment by denniskniep** [comment]
I am also interested in this feature

@csuzhangxc  In case of Prometheus Operator it uses the service definition to create scrape configs that covers all backing pods
see here: 
https://prometheus-operator.dev/docs/developer/getting-started/#using-servicemonitors
https://github.com/prometheus-operator/prometheus-operator?tab=readme-ov-file#customresourcedefinitions

> ServiceMonitor, which declaratively specifies how groups of Kubernetes services should be monitored. The Operator automatically generates Prometheus scrape configuration based on the current state of the objects in the API server.

So from my point of view it is a valid use case to expose also the metrics port in the tikv peer service (20180) 

EDIT: 
I think it does not work, because its a Headless service.

But anyhow it would be beneficial to list the port 20180 in the tikv pod e.g.
```
  container:
    ports:
    - containerPort: 20160
      name: server
      protocol: TCP
    - containerPort: 20180
      name: status
      protocol: TCP
```

As it is already noted in the annotations:
```
annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "20180"
  prometheus.io/scrape: "true"
```

As workaround until this is implemented  one can patch the tikv container

```
tikv:
    additionalContainers:
      - name: tikv
        image: pingcap/tikv:v8.5.2        
        ports:
          - containerPort: 20180
            name: status
            protocol: TCP
```
