### ISSUE TITLE
Invalid backup does not fail `VolumeBackup`

### ISSUE THREAD

**Issue by michaelmdeng** [pingcap/tidb-operator#6090]
## Bug Report

**What version of Kubernetes are you using?**

1.27.14

**What version of TiDB Operator are you using?**

v1.5.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Misconfigure an EBS snapshot `VolumeBackup`. This causes the underlying data-plane `Backup` to enter into `Invalid` state

```
$ kubectl  get bk <> -o yaml | yq .status
status:
  conditions:
  - lastTransitionTime: "2025-02-19T02:00:26Z"
    message: not support backup TiDB cluster with no tikv replica
    reason: InvalidSpec
    status: "True"
    type: Invalid
  phase: Invalid
  timeCompleted: null
  timeStarted: null
ttlSecondsAfterFinished: 3600
```

However, this is not considered a terminal state and the overarching `VolumeBackup` continues to run

```
kubectl get vbk <> -o yaml | yq .status
status:
  backups:
  - backupName: <>
    k8sClusterName: <>
    phase: Invalid
    tcName: <>
    tcNamespace: <>
  conditions:
  - lastTransitionTime: "2025-02-19T02:00:26Z"
    status: "True"
    type: Running
  phase: Running
  timeCompleted: null
  timeStarted: "2025-02-19T02:00:26Z"
ttlSecondsAfterFinished: 3600
```

The `VolumeBackup` never fails and is stuck. When part of a schedule, this blocks processing of subsequent backups on schedule.

**What did you expect to see?**

When `Backup` configuration is invalid, `Backup` and `VolumeBackup` should fail and schedule should continue attempting subsequent backups

**What did you see instead?**

`VolumeBackup` stays in running state and blocks subsequent backups
