### ISSUE TITLE
Helm install failed "Deployment in version "v1beta1" cannot be handled as a Deployment:"

### ISSUE THREAD

**Issue by NanXuejiao** [pingcap/tidb-operator#727]
I deploy TiDB on k8s following  [here](https://pingcap.com/docs-cn/v3.0/tidb-in-kubernetes/deploy/tidb-operator) . and face issue when execute `helm install ...`
```
$ helm inspect values pingcap/tidb-operator --version=v1.0.0 tidb/tidb-operator/values-tidb-operator.yaml

Error: release tidb-operator failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment.Spec: v1beta1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|scheduler","memory":|..., bigger context ...|ubeSchedulerImageName":"k8s.gcr.io/kube-scheduler","memory":"50Mi"}}},{"command":["kube-scheduler","|...
```
 Then, I look resource at `tidb-admin` namespace.
```
$  kubectl get po -n tidb-admin -l app.kubernetes.io/name=tidb-operator
NAME                                       READY   STATUS    RESTARTS   AGE
tidb-controller-manager-5495964fd8-lv856   1/1     Running   0          16m
```

Kubernetes version is `v1.13.4`, and I'm sure Kubernetes work well.
TiDB Operator version is `v1.0.0`.

**Comment by weekface** [comment]
@NanXuejiao  What does your file `tidb/tidb-operator/values-tidb-operator.yaml` look like?

**Comment by NanXuejiao** [comment]
@weekface  I get it by ` helm inspect values pingcap/tidb-operator --version=v1.0.0 > tidb/tidb-operator/values-tidb-operator.yaml `
```
clusterScoped: true
rbac:
  create: true
operatorImage: pingcap/tidb-operator:v1.0.0
imagePullPolicy: IfNotPresent

defaultStorageClassName: local-storage

controllerManager:
  serviceAccount: tidb-controller-manager
  logLevel: 2
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
  autoFailover: true
  # pd failover period default(5m)
  pdFailoverPeriod: 5m
  # tikv failover period default(5m)
  tikvFailoverPeriod: 5m
  # tidb failover period default(5m)
  tidbFailoverPeriod: 5m

scheduler:
  serviceAccount: tidb-scheduler
  logLevel: 2
  replicas: 1
  schedulerName: tidb-scheduler
  # features:
  # - StableScheduling=true
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
      kubeSchedulerImageName: k8s.gcr.io/kube-scheduler
  # kubeSchedulerImageTag:
```

**Comment by weekface** [comment]
I suppose the indent of `kubeSchedulerImageName:` is not corrent, now is:

```
scheduler:
  serviceAccount: tidb-scheduler
  logLevel: 2
  replicas: 1
  schedulerName: tidb-scheduler
  # features:
  # - StableScheduling=true
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
      kubeSchedulerImageName: k8s.gcr.io/kube-scheduler
  # kubeSchedulerImageTag:
```

It should be:

```
scheduler:
  serviceAccount: tidb-scheduler
  logLevel: 2
  replicas: 1
  schedulerName: tidb-scheduler
  # features:
  # - StableScheduling=true
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
  kubeSchedulerImageName: k8s.gcr.io/kube-scheduler
  # kubeSchedulerImageTag:

```
